#!/bin/bash
set -e

echo "[install-server] downloading Satisfactory dedicated server via SteamCMD (app 1690800)"
steamcmd.sh \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 1690800 -beta public validate \
    +quit

echo "[install-server] Satisfactory dedicated server installed"
