#!/bin/bash
set -e

echo "[update-server] updating Satisfactory dedicated server via SteamCMD"
steamcmd.sh \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 1690800 -beta public validate \
    +quit

echo "[update-server] update complete"
