#!/bin/bash
set -e

echo "[update-server] updating ARK dedicated server via SteamCMD"
steamcmd-retry \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 376030 validate \
    +quit

echo "[update-server] update complete"
