#!/bin/bash
if [ -z "$1" ]; then
    echo "[send-command] usage: send-command <command>"
    exit 1
fi

RCON_PORT="${RCON_PORT:-28016}"
RCON_PASSWORD="${RCON_PASSWORD:-changeme}"

rcon -a "localhost:${RCON_PORT}" -p "$RCON_PASSWORD" "$1"
