// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: content_manifest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentManifestPayload struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Mappings      []*ContentManifestPayload_FileMapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentManifestPayload) Reset() {
	*x = ContentManifestPayload{}
	mi := &file_content_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentManifestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentManifestPayload) ProtoMessage() {}

func (x *ContentManifestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_content_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentManifestPayload.ProtoReflect.Descriptor instead.
func (*ContentManifestPayload) Descriptor() ([]byte, []int) {
	return file_content_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *ContentManifestPayload) GetMappings() []*ContentManifestPayload_FileMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type ContentManifestMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DepotId            *uint32                `protobuf:"varint,1,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	GidManifest        *uint64                `protobuf:"varint,2,opt,name=gid_manifest,json=gidManifest" json:"gid_manifest,omitempty"`
	CreationTime       *uint32                `protobuf:"varint,3,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	FilenamesEncrypted *bool                  `protobuf:"varint,4,opt,name=filenames_encrypted,json=filenamesEncrypted" json:"filenames_encrypted,omitempty"`
	CbDiskOriginal     *uint64                `protobuf:"varint,5,opt,name=cb_disk_original,json=cbDiskOriginal" json:"cb_disk_original,omitempty"`
	CbDiskCompressed   *uint64                `protobuf:"varint,6,opt,name=cb_disk_compressed,json=cbDiskCompressed" json:"cb_disk_compressed,omitempty"`
	UniqueChunks       *uint32                `protobuf:"varint,7,opt,name=unique_chunks,json=uniqueChunks" json:"unique_chunks,omitempty"`
	CrcEncrypted       *uint32                `protobuf:"varint,8,opt,name=crc_encrypted,json=crcEncrypted" json:"crc_encrypted,omitempty"`
	CrcClear           *uint32                `protobuf:"varint,9,opt,name=crc_clear,json=crcClear" json:"crc_clear,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ContentManifestMetadata) Reset() {
	*x = ContentManifestMetadata{}
	mi := &file_content_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentManifestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentManifestMetadata) ProtoMessage() {}

func (x *ContentManifestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_content_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentManifestMetadata.ProtoReflect.Descriptor instead.
func (*ContentManifestMetadata) Descriptor() ([]byte, []int) {
	return file_content_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ContentManifestMetadata) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *ContentManifestMetadata) GetGidManifest() uint64 {
	if x != nil && x.GidManifest != nil {
		return *x.GidManifest
	}
	return 0
}

func (x *ContentManifestMetadata) GetCreationTime() uint32 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return 0
}

func (x *ContentManifestMetadata) GetFilenamesEncrypted() bool {
	if x != nil && x.FilenamesEncrypted != nil {
		return *x.FilenamesEncrypted
	}
	return false
}

func (x *ContentManifestMetadata) GetCbDiskOriginal() uint64 {
	if x != nil && x.CbDiskOriginal != nil {
		return *x.CbDiskOriginal
	}
	return 0
}

func (x *ContentManifestMetadata) GetCbDiskCompressed() uint64 {
	if x != nil && x.CbDiskCompressed != nil {
		return *x.CbDiskCompressed
	}
	return 0
}

func (x *ContentManifestMetadata) GetUniqueChunks() uint32 {
	if x != nil && x.UniqueChunks != nil {
		return *x.UniqueChunks
	}
	return 0
}

func (x *ContentManifestMetadata) GetCrcEncrypted() uint32 {
	if x != nil && x.CrcEncrypted != nil {
		return *x.CrcEncrypted
	}
	return 0
}

func (x *ContentManifestMetadata) GetCrcClear() uint32 {
	if x != nil && x.CrcClear != nil {
		return *x.CrcClear
	}
	return 0
}

type ContentManifestPayload_FileMapping struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Filename      *string                                         `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Size          *uint64                                         `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Flags         *uint32                                         `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	ShaFilename   []byte                                          `protobuf:"bytes,4,opt,name=sha_filename,json=shaFilename" json:"sha_filename,omitempty"`
	ShaContent    []byte                                          `protobuf:"bytes,5,opt,name=sha_content,json=shaContent" json:"sha_content,omitempty"`
	Chunks        []*ContentManifestPayload_FileMapping_ChunkData `protobuf:"bytes,6,rep,name=chunks" json:"chunks,omitempty"`
	Linktarget    *string                                         `protobuf:"bytes,7,opt,name=linktarget" json:"linktarget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentManifestPayload_FileMapping) Reset() {
	*x = ContentManifestPayload_FileMapping{}
	mi := &file_content_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentManifestPayload_FileMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentManifestPayload_FileMapping) ProtoMessage() {}

func (x *ContentManifestPayload_FileMapping) ProtoReflect() protoreflect.Message {
	mi := &file_content_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentManifestPayload_FileMapping.ProtoReflect.Descriptor instead.
func (*ContentManifestPayload_FileMapping) Descriptor() ([]byte, []int) {
	return file_content_manifest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ContentManifestPayload_FileMapping) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *ContentManifestPayload_FileMapping) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ContentManifestPayload_FileMapping) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *ContentManifestPayload_FileMapping) GetShaFilename() []byte {
	if x != nil {
		return x.ShaFilename
	}
	return nil
}

func (x *ContentManifestPayload_FileMapping) GetShaContent() []byte {
	if x != nil {
		return x.ShaContent
	}
	return nil
}

func (x *ContentManifestPayload_FileMapping) GetChunks() []*ContentManifestPayload_FileMapping_ChunkData {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ContentManifestPayload_FileMapping) GetLinktarget() string {
	if x != nil && x.Linktarget != nil {
		return *x.Linktarget
	}
	return ""
}

type ContentManifestPayload_FileMapping_ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           []byte                 `protobuf:"bytes,1,opt,name=sha" json:"sha,omitempty"`
	Crc           *uint32                `protobuf:"fixed32,2,opt,name=crc" json:"crc,omitempty"`
	Offset        *uint64                `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	CbOriginal    *uint32                `protobuf:"varint,4,opt,name=cb_original,json=cbOriginal" json:"cb_original,omitempty"`
	CbCompressed  *uint32                `protobuf:"varint,5,opt,name=cb_compressed,json=cbCompressed" json:"cb_compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentManifestPayload_FileMapping_ChunkData) Reset() {
	*x = ContentManifestPayload_FileMapping_ChunkData{}
	mi := &file_content_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentManifestPayload_FileMapping_ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentManifestPayload_FileMapping_ChunkData) ProtoMessage() {}

func (x *ContentManifestPayload_FileMapping_ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_content_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentManifestPayload_FileMapping_ChunkData.ProtoReflect.Descriptor instead.
func (*ContentManifestPayload_FileMapping_ChunkData) Descriptor() ([]byte, []int) {
	return file_content_manifest_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ContentManifestPayload_FileMapping_ChunkData) GetSha() []byte {
	if x != nil {
		return x.Sha
	}
	return nil
}

func (x *ContentManifestPayload_FileMapping_ChunkData) GetCrc() uint32 {
	if x != nil && x.Crc != nil {
		return *x.Crc
	}
	return 0
}

func (x *ContentManifestPayload_FileMapping_ChunkData) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ContentManifestPayload_FileMapping_ChunkData) GetCbOriginal() uint32 {
	if x != nil && x.CbOriginal != nil {
		return *x.CbOriginal
	}
	return 0
}

func (x *ContentManifestPayload_FileMapping_ChunkData) GetCbCompressed() uint32 {
	if x != nil && x.CbCompressed != nil {
		return *x.CbCompressed
	}
	return 0
}

var File_content_manifest_proto protoreflect.FileDescriptor

const file_content_manifest_proto_rawDesc = "" +
	"\n" +
	"\x16content_manifest.proto\"\xea\x03\n" +
	"\x16ContentManifestPayload\x12?\n" +
	"\bmappings\x18\x01 \x03(\v2#.ContentManifestPayload.FileMappingR\bmappings\x1a\x8e\x03\n" +
	"\vFileMapping\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x12!\n" +
	"\fsha_filename\x18\x04 \x01(\fR\vshaFilename\x12\x1f\n" +
	"\vsha_content\x18\x05 \x01(\fR\n" +
	"shaContent\x12E\n" +
	"\x06chunks\x18\x06 \x03(\v2-.ContentManifestPayload.FileMapping.ChunkDataR\x06chunks\x12\x1e\n" +
	"\n" +
	"linktarget\x18\a \x01(\tR\n" +
	"linktarget\x1a\x8d\x01\n" +
	"\tChunkData\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\fR\x03sha\x12\x10\n" +
	"\x03crc\x18\x02 \x01(\aR\x03crc\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x1f\n" +
	"\vcb_original\x18\x04 \x01(\rR\n" +
	"cbOriginal\x12#\n" +
	"\rcb_compressed\x18\x05 \x01(\rR\fcbCompressed\"\xec\x02\n" +
	"\x17ContentManifestMetadata\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\rR\adepotId\x12!\n" +
	"\fgid_manifest\x18\x02 \x01(\x04R\vgidManifest\x12#\n" +
	"\rcreation_time\x18\x03 \x01(\rR\fcreationTime\x12/\n" +
	"\x13filenames_encrypted\x18\x04 \x01(\bR\x12filenamesEncrypted\x12(\n" +
	"\x10cb_disk_original\x18\x05 \x01(\x04R\x0ecbDiskOriginal\x12,\n" +
	"\x12cb_disk_compressed\x18\x06 \x01(\x04R\x10cbDiskCompressed\x12#\n" +
	"\runique_chunks\x18\a \x01(\rR\funiqueChunks\x12#\n" +
	"\rcrc_encrypted\x18\b \x01(\rR\fcrcEncrypted\x12\x1b\n" +
	"\tcrc_clear\x18\t \x01(\rR\bcrcClearB\x05H\x01\x80\x01\x00"

var (
	file_content_manifest_proto_rawDescOnce sync.Once
	file_content_manifest_proto_rawDescData []byte
)

func file_content_manifest_proto_rawDescGZIP() []byte {
	file_content_manifest_proto_rawDescOnce.Do(func() {
		file_content_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_manifest_proto_rawDesc), len(file_content_manifest_proto_rawDesc)))
	})
	return file_content_manifest_proto_rawDescData
}

var file_content_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_content_manifest_proto_goTypes = []any{
	(*ContentManifestPayload)(nil),                       // 0: ContentManifestPayload
	(*ContentManifestMetadata)(nil),                      // 1: ContentManifestMetadata
	(*ContentManifestPayload_FileMapping)(nil),           // 2: ContentManifestPayload.FileMapping
	(*ContentManifestPayload_FileMapping_ChunkData)(nil), // 3: ContentManifestPayload.FileMapping.ChunkData
}
var file_content_manifest_proto_depIdxs = []int32{
	2, // 0: ContentManifestPayload.mappings:type_name -> ContentManifestPayload.FileMapping
	3, // 1: ContentManifestPayload.FileMapping.chunks:type_name -> ContentManifestPayload.FileMapping.ChunkData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_content_manifest_proto_init() }
func file_content_manifest_proto_init() {
	if File_content_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_manifest_proto_rawDesc), len(file_content_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_manifest_proto_goTypes,
		DependencyIndexes: file_content_manifest_proto_depIdxs,
		MessageInfos:      file_content_manifest_proto_msgTypes,
	}.Build()
	File_content_manifest_proto = out.File
	file_content_manifest_proto_goTypes = nil
	file_content_manifest_proto_depIdxs = nil
}
