// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: enums.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ESessionPersistence int32

const (
	ESessionPersistence_k_ESessionPersistence_Invalid    ESessionPersistence = -1
	ESessionPersistence_k_ESessionPersistence_Ephemeral  ESessionPersistence = 0
	ESessionPersistence_k_ESessionPersistence_Persistent ESessionPersistence = 1
)

// Enum value maps for ESessionPersistence.
var (
	ESessionPersistence_name = map[int32]string{
		-1: "k_ESessionPersistence_Invalid",
		0:  "k_ESessionPersistence_Ephemeral",
		1:  "k_ESessionPersistence_Persistent",
	}
	ESessionPersistence_value = map[string]int32{
		"k_ESessionPersistence_Invalid":    -1,
		"k_ESessionPersistence_Ephemeral":  0,
		"k_ESessionPersistence_Persistent": 1,
	}
)

func (x ESessionPersistence) Enum() *ESessionPersistence {
	p := new(ESessionPersistence)
	*p = x
	return p
}

func (x ESessionPersistence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESessionPersistence) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_proto_enumTypes[0].Descriptor()
}

func (ESessionPersistence) Type() protoreflect.EnumType {
	return &file_enums_proto_enumTypes[0]
}

func (x ESessionPersistence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ESessionPersistence) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ESessionPersistence(num)
	return nil
}

// Deprecated: Use ESessionPersistence.Descriptor instead.
func (ESessionPersistence) EnumDescriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{0}
}

var File_enums_proto protoreflect.FileDescriptor

const file_enums_proto_rawDesc = "" +
	"\n" +
	"\venums.proto*\x8c\x01\n" +
	"\x13ESessionPersistence\x12*\n" +
	"\x1dk_ESessionPersistence_Invalid\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x1fk_ESessionPersistence_Ephemeral\x10\x00\x12$\n" +
	" k_ESessionPersistence_Persistent\x10\x01B\x02H\x01"

var (
	file_enums_proto_rawDescOnce sync.Once
	file_enums_proto_rawDescData []byte
)

func file_enums_proto_rawDescGZIP() []byte {
	file_enums_proto_rawDescOnce.Do(func() {
		file_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_proto_rawDesc), len(file_enums_proto_rawDesc)))
	})
	return file_enums_proto_rawDescData
}

var file_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_proto_goTypes = []any{
	(ESessionPersistence)(0), // 0: ESessionPersistence
}
var file_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_proto_init() }
func file_enums_proto_init() {
	if File_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_proto_rawDesc), len(file_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_proto_goTypes,
		DependencyIndexes: file_enums_proto_depIdxs,
		EnumInfos:         file_enums_proto_enumTypes,
	}.Build()
	File_enums_proto = out.File
	file_enums_proto_goTypes = nil
	file_enums_proto_depIdxs = nil
}
