// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_clientserver_2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientGetDepotDecryptionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepotId       *uint32                `protobuf:"varint,1,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	AppId         *uint32                `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientGetDepotDecryptionKey) Reset() {
	*x = CMsgClientGetDepotDecryptionKey{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientGetDepotDecryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientGetDepotDecryptionKey) ProtoMessage() {}

func (x *CMsgClientGetDepotDecryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientGetDepotDecryptionKey.ProtoReflect.Descriptor instead.
func (*CMsgClientGetDepotDecryptionKey) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientGetDepotDecryptionKey) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CMsgClientGetDepotDecryptionKey) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type CMsgClientGetDepotDecryptionKeyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Eresult            *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DepotId            *uint32                `protobuf:"varint,2,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	DepotEncryptionKey []byte                 `protobuf:"bytes,3,opt,name=depot_encryption_key,json=depotEncryptionKey" json:"depot_encryption_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CMsgClientGetDepotDecryptionKeyResponse fields.
const (
	Default_CMsgClientGetDepotDecryptionKeyResponse_Eresult = int32(2)
)

func (x *CMsgClientGetDepotDecryptionKeyResponse) Reset() {
	*x = CMsgClientGetDepotDecryptionKeyResponse{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientGetDepotDecryptionKeyResponse) ProtoMessage() {}

func (x *CMsgClientGetDepotDecryptionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientGetDepotDecryptionKeyResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientGetDepotDecryptionKeyResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientGetDepotDecryptionKeyResponse_Eresult
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetDepotEncryptionKey() []byte {
	if x != nil {
		return x.DepotEncryptionKey
	}
	return nil
}

var File_steammessages_clientserver_2_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_2_proto_rawDesc = "" +
	"\n" +
	"\"steammessages_clientserver_2.proto\"S\n" +
	"\x1fCMsgClientGetDepotDecryptionKey\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\rR\adepotId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\"\x93\x01\n" +
	"'CMsgClientGetDepotDecryptionKeyResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12\x19\n" +
	"\bdepot_id\x18\x02 \x01(\rR\adepotId\x120\n" +
	"\x14depot_encryption_key\x18\x03 \x01(\fR\x12depotEncryptionKeyB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_2_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_2_proto_rawDescData []byte
)

func file_steammessages_clientserver_2_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_2_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_2_proto_rawDesc), len(file_steammessages_clientserver_2_proto_rawDesc)))
	})
	return file_steammessages_clientserver_2_proto_rawDescData
}

var file_steammessages_clientserver_2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steammessages_clientserver_2_proto_goTypes = []any{
	(*CMsgClientGetDepotDecryptionKey)(nil),         // 0: CMsgClientGetDepotDecryptionKey
	(*CMsgClientGetDepotDecryptionKeyResponse)(nil), // 1: CMsgClientGetDepotDecryptionKeyResponse
}
var file_steammessages_clientserver_2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_2_proto_init() }
func file_steammessages_clientserver_2_proto_init() {
	if File_steammessages_clientserver_2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_2_proto_rawDesc), len(file_steammessages_clientserver_2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_2_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_2_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_2_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_2_proto = out.File
	file_steammessages_clientserver_2_proto_goTypes = nil
	file_steammessages_clientserver_2_proto_depIdxs = nil
}
