// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgProtoBufHeader_ESessionDisposition int32

const (
	CMsgProtoBufHeader_k_ESessionDispositionNormal     CMsgProtoBufHeader_ESessionDisposition = 0
	CMsgProtoBufHeader_k_ESessionDispositionDisconnect CMsgProtoBufHeader_ESessionDisposition = 1
)

// Enum value maps for CMsgProtoBufHeader_ESessionDisposition.
var (
	CMsgProtoBufHeader_ESessionDisposition_name = map[int32]string{
		0: "k_ESessionDispositionNormal",
		1: "k_ESessionDispositionDisconnect",
	}
	CMsgProtoBufHeader_ESessionDisposition_value = map[string]int32{
		"k_ESessionDispositionNormal":     0,
		"k_ESessionDispositionDisconnect": 1,
	}
)

func (x CMsgProtoBufHeader_ESessionDisposition) Enum() *CMsgProtoBufHeader_ESessionDisposition {
	p := new(CMsgProtoBufHeader_ESessionDisposition)
	*p = x
	return p
}

func (x CMsgProtoBufHeader_ESessionDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgProtoBufHeader_ESessionDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_base_proto_enumTypes[0].Descriptor()
}

func (CMsgProtoBufHeader_ESessionDisposition) Type() protoreflect.EnumType {
	return &file_steammessages_base_proto_enumTypes[0]
}

func (x CMsgProtoBufHeader_ESessionDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgProtoBufHeader_ESessionDisposition) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgProtoBufHeader_ESessionDisposition(num)
	return nil
}

// Deprecated: Use CMsgProtoBufHeader_ESessionDisposition.Descriptor instead.
func (CMsgProtoBufHeader_ESessionDisposition) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_base_proto_rawDescGZIP(), []int{2, 0}
}

type CMsgIPAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ip:
	//
	//	*CMsgIPAddress_V4
	//	*CMsgIPAddress_V6
	Ip            isCMsgIPAddress_Ip `protobuf_oneof:"ip"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgIPAddress) Reset() {
	*x = CMsgIPAddress{}
	mi := &file_steammessages_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgIPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgIPAddress) ProtoMessage() {}

func (x *CMsgIPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgIPAddress.ProtoReflect.Descriptor instead.
func (*CMsgIPAddress) Descriptor() ([]byte, []int) {
	return file_steammessages_base_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgIPAddress) GetIp() isCMsgIPAddress_Ip {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *CMsgIPAddress) GetV4() uint32 {
	if x != nil {
		if x, ok := x.Ip.(*CMsgIPAddress_V4); ok {
			return x.V4
		}
	}
	return 0
}

func (x *CMsgIPAddress) GetV6() []byte {
	if x != nil {
		if x, ok := x.Ip.(*CMsgIPAddress_V6); ok {
			return x.V6
		}
	}
	return nil
}

type isCMsgIPAddress_Ip interface {
	isCMsgIPAddress_Ip()
}

type CMsgIPAddress_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,oneof"`
}

type CMsgIPAddress_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,oneof"`
}

func (*CMsgIPAddress_V4) isCMsgIPAddress_Ip() {}

func (*CMsgIPAddress_V6) isCMsgIPAddress_Ip() {}

type CMsgGCRoutingProtoBufHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstGcidQueue  *uint64                `protobuf:"varint,1,opt,name=dst_gcid_queue,json=dstGcidQueue" json:"dst_gcid_queue,omitempty"`
	DstGcDirIndex *uint32                `protobuf:"varint,2,opt,name=dst_gc_dir_index,json=dstGcDirIndex" json:"dst_gc_dir_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGCRoutingProtoBufHeader) Reset() {
	*x = CMsgGCRoutingProtoBufHeader{}
	mi := &file_steammessages_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCRoutingProtoBufHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCRoutingProtoBufHeader) ProtoMessage() {}

func (x *CMsgGCRoutingProtoBufHeader) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCRoutingProtoBufHeader.ProtoReflect.Descriptor instead.
func (*CMsgGCRoutingProtoBufHeader) Descriptor() ([]byte, []int) {
	return file_steammessages_base_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgGCRoutingProtoBufHeader) GetDstGcidQueue() uint64 {
	if x != nil && x.DstGcidQueue != nil {
		return *x.DstGcidQueue
	}
	return 0
}

func (x *CMsgGCRoutingProtoBufHeader) GetDstGcDirIndex() uint32 {
	if x != nil && x.DstGcDirIndex != nil {
		return *x.DstGcDirIndex
	}
	return 0
}

type CMsgProtoBufHeader struct {
	state                       protoimpl.MessageState                  `protogen:"open.v1"`
	Steamid                     *uint64                                 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ClientSessionid             *int32                                  `protobuf:"varint,2,opt,name=client_sessionid,json=clientSessionid" json:"client_sessionid,omitempty"`
	RoutingAppid                *uint32                                 `protobuf:"varint,3,opt,name=routing_appid,json=routingAppid" json:"routing_appid,omitempty"`
	JobidSource                 *uint64                                 `protobuf:"fixed64,10,opt,name=jobid_source,json=jobidSource,def=18446744073709551615" json:"jobid_source,omitempty"`
	JobidTarget                 *uint64                                 `protobuf:"fixed64,11,opt,name=jobid_target,json=jobidTarget,def=18446744073709551615" json:"jobid_target,omitempty"`
	TargetJobName               *string                                 `protobuf:"bytes,12,opt,name=target_job_name,json=targetJobName" json:"target_job_name,omitempty"`
	SeqNum                      *int32                                  `protobuf:"varint,24,opt,name=seq_num,json=seqNum" json:"seq_num,omitempty"`
	Eresult                     *int32                                  `protobuf:"varint,13,opt,name=eresult,def=2" json:"eresult,omitempty"`
	ErrorMessage                *string                                 `protobuf:"bytes,14,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	AuthAccountFlags            *uint32                                 `protobuf:"varint,16,opt,name=auth_account_flags,json=authAccountFlags" json:"auth_account_flags,omitempty"`
	TokenSource                 *uint32                                 `protobuf:"varint,22,opt,name=token_source,json=tokenSource" json:"token_source,omitempty"`
	AdminSpoofingUser           *bool                                   `protobuf:"varint,23,opt,name=admin_spoofing_user,json=adminSpoofingUser" json:"admin_spoofing_user,omitempty"`
	TransportError              *int32                                  `protobuf:"varint,17,opt,name=transport_error,json=transportError,def=1" json:"transport_error,omitempty"`
	Messageid                   *uint64                                 `protobuf:"varint,18,opt,name=messageid,def=18446744073709551615" json:"messageid,omitempty"`
	PublisherGroupId            *uint32                                 `protobuf:"varint,19,opt,name=publisher_group_id,json=publisherGroupId" json:"publisher_group_id,omitempty"`
	Sysid                       *uint32                                 `protobuf:"varint,20,opt,name=sysid" json:"sysid,omitempty"`
	WebapiKeyId                 *uint32                                 `protobuf:"varint,25,opt,name=webapi_key_id,json=webapiKeyId" json:"webapi_key_id,omitempty"`
	IsFromExternalSource        *bool                                   `protobuf:"varint,26,opt,name=is_from_external_source,json=isFromExternalSource" json:"is_from_external_source,omitempty"`
	ForwardToSysid              []uint32                                `protobuf:"varint,27,rep,name=forward_to_sysid,json=forwardToSysid" json:"forward_to_sysid,omitempty"`
	CmSysid                     *uint32                                 `protobuf:"varint,28,opt,name=cm_sysid,json=cmSysid" json:"cm_sysid,omitempty"`
	LauncherType                *uint32                                 `protobuf:"varint,31,opt,name=launcher_type,json=launcherType,def=0" json:"launcher_type,omitempty"`
	Realm                       *uint32                                 `protobuf:"varint,32,opt,name=realm,def=0" json:"realm,omitempty"`
	TimeoutMs                   *int32                                  `protobuf:"varint,33,opt,name=timeout_ms,json=timeoutMs,def=-1" json:"timeout_ms,omitempty"`
	DebugSource                 *string                                 `protobuf:"bytes,34,opt,name=debug_source,json=debugSource" json:"debug_source,omitempty"`
	DebugSourceStringIndex      *uint32                                 `protobuf:"varint,35,opt,name=debug_source_string_index,json=debugSourceStringIndex" json:"debug_source_string_index,omitempty"`
	TokenId                     *uint64                                 `protobuf:"varint,36,opt,name=token_id,json=tokenId" json:"token_id,omitempty"`
	RoutingGc                   *CMsgGCRoutingProtoBufHeader            `protobuf:"bytes,37,opt,name=routing_gc,json=routingGc" json:"routing_gc,omitempty"`
	SessionDisposition          *CMsgProtoBufHeader_ESessionDisposition `protobuf:"varint,38,opt,name=session_disposition,json=sessionDisposition,enum=CMsgProtoBufHeader_ESessionDisposition,def=0" json:"session_disposition,omitempty"`
	WgToken                     *string                                 `protobuf:"bytes,39,opt,name=wg_token,json=wgToken" json:"wg_token,omitempty"`
	WebuiAuthKey                *string                                 `protobuf:"bytes,40,opt,name=webui_auth_key,json=webuiAuthKey" json:"webui_auth_key,omitempty"`
	ExcludeClientSessionids     []int32                                 `protobuf:"varint,41,rep,name=exclude_client_sessionids,json=excludeClientSessionids" json:"exclude_client_sessionids,omitempty"`
	AdminRequestSpoofingSteamid *uint64                                 `protobuf:"fixed64,43,opt,name=admin_request_spoofing_steamid,json=adminRequestSpoofingSteamid" json:"admin_request_spoofing_steamid,omitempty"`
	IsValveds                   *bool                                   `protobuf:"varint,44,opt,name=is_valveds,json=isValveds" json:"is_valveds,omitempty"`
	TraceTag                    *uint64                                 `protobuf:"fixed64,45,opt,name=trace_tag,json=traceTag" json:"trace_tag,omitempty"`
	// Types that are valid to be assigned to IpAddr:
	//
	//	*CMsgProtoBufHeader_Ip
	//	*CMsgProtoBufHeader_IpV6
	IpAddr        isCMsgProtoBufHeader_IpAddr `protobuf_oneof:"ip_addr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgProtoBufHeader fields.
const (
	Default_CMsgProtoBufHeader_JobidSource        = uint64(18446744073709551615)
	Default_CMsgProtoBufHeader_JobidTarget        = uint64(18446744073709551615)
	Default_CMsgProtoBufHeader_Eresult            = int32(2)
	Default_CMsgProtoBufHeader_TransportError     = int32(1)
	Default_CMsgProtoBufHeader_Messageid          = uint64(18446744073709551615)
	Default_CMsgProtoBufHeader_LauncherType       = uint32(0)
	Default_CMsgProtoBufHeader_Realm              = uint32(0)
	Default_CMsgProtoBufHeader_TimeoutMs          = int32(-1)
	Default_CMsgProtoBufHeader_SessionDisposition = CMsgProtoBufHeader_k_ESessionDispositionNormal
)

func (x *CMsgProtoBufHeader) Reset() {
	*x = CMsgProtoBufHeader{}
	mi := &file_steammessages_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgProtoBufHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgProtoBufHeader) ProtoMessage() {}

func (x *CMsgProtoBufHeader) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgProtoBufHeader.ProtoReflect.Descriptor instead.
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) {
	return file_steammessages_base_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgProtoBufHeader) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetClientSessionid() int32 {
	if x != nil && x.ClientSessionid != nil {
		return *x.ClientSessionid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetRoutingAppid() uint32 {
	if x != nil && x.RoutingAppid != nil {
		return *x.RoutingAppid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetJobidSource() uint64 {
	if x != nil && x.JobidSource != nil {
		return *x.JobidSource
	}
	return Default_CMsgProtoBufHeader_JobidSource
}

func (x *CMsgProtoBufHeader) GetJobidTarget() uint64 {
	if x != nil && x.JobidTarget != nil {
		return *x.JobidTarget
	}
	return Default_CMsgProtoBufHeader_JobidTarget
}

func (x *CMsgProtoBufHeader) GetTargetJobName() string {
	if x != nil && x.TargetJobName != nil {
		return *x.TargetJobName
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetSeqNum() int32 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgProtoBufHeader_Eresult
}

func (x *CMsgProtoBufHeader) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetAuthAccountFlags() uint32 {
	if x != nil && x.AuthAccountFlags != nil {
		return *x.AuthAccountFlags
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetTokenSource() uint32 {
	if x != nil && x.TokenSource != nil {
		return *x.TokenSource
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetAdminSpoofingUser() bool {
	if x != nil && x.AdminSpoofingUser != nil {
		return *x.AdminSpoofingUser
	}
	return false
}

func (x *CMsgProtoBufHeader) GetTransportError() int32 {
	if x != nil && x.TransportError != nil {
		return *x.TransportError
	}
	return Default_CMsgProtoBufHeader_TransportError
}

func (x *CMsgProtoBufHeader) GetMessageid() uint64 {
	if x != nil && x.Messageid != nil {
		return *x.Messageid
	}
	return Default_CMsgProtoBufHeader_Messageid
}

func (x *CMsgProtoBufHeader) GetPublisherGroupId() uint32 {
	if x != nil && x.PublisherGroupId != nil {
		return *x.PublisherGroupId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetSysid() uint32 {
	if x != nil && x.Sysid != nil {
		return *x.Sysid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetWebapiKeyId() uint32 {
	if x != nil && x.WebapiKeyId != nil {
		return *x.WebapiKeyId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetIsFromExternalSource() bool {
	if x != nil && x.IsFromExternalSource != nil {
		return *x.IsFromExternalSource
	}
	return false
}

func (x *CMsgProtoBufHeader) GetForwardToSysid() []uint32 {
	if x != nil {
		return x.ForwardToSysid
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetCmSysid() uint32 {
	if x != nil && x.CmSysid != nil {
		return *x.CmSysid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetLauncherType() uint32 {
	if x != nil && x.LauncherType != nil {
		return *x.LauncherType
	}
	return Default_CMsgProtoBufHeader_LauncherType
}

func (x *CMsgProtoBufHeader) GetRealm() uint32 {
	if x != nil && x.Realm != nil {
		return *x.Realm
	}
	return Default_CMsgProtoBufHeader_Realm
}

func (x *CMsgProtoBufHeader) GetTimeoutMs() int32 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return Default_CMsgProtoBufHeader_TimeoutMs
}

func (x *CMsgProtoBufHeader) GetDebugSource() string {
	if x != nil && x.DebugSource != nil {
		return *x.DebugSource
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetDebugSourceStringIndex() uint32 {
	if x != nil && x.DebugSourceStringIndex != nil {
		return *x.DebugSourceStringIndex
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetTokenId() uint64 {
	if x != nil && x.TokenId != nil {
		return *x.TokenId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetRoutingGc() *CMsgGCRoutingProtoBufHeader {
	if x != nil {
		return x.RoutingGc
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetSessionDisposition() CMsgProtoBufHeader_ESessionDisposition {
	if x != nil && x.SessionDisposition != nil {
		return *x.SessionDisposition
	}
	return Default_CMsgProtoBufHeader_SessionDisposition
}

func (x *CMsgProtoBufHeader) GetWgToken() string {
	if x != nil && x.WgToken != nil {
		return *x.WgToken
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetWebuiAuthKey() string {
	if x != nil && x.WebuiAuthKey != nil {
		return *x.WebuiAuthKey
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetExcludeClientSessionids() []int32 {
	if x != nil {
		return x.ExcludeClientSessionids
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetAdminRequestSpoofingSteamid() uint64 {
	if x != nil && x.AdminRequestSpoofingSteamid != nil {
		return *x.AdminRequestSpoofingSteamid
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetIsValveds() bool {
	if x != nil && x.IsValveds != nil {
		return *x.IsValveds
	}
	return false
}

func (x *CMsgProtoBufHeader) GetTraceTag() uint64 {
	if x != nil && x.TraceTag != nil {
		return *x.TraceTag
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetIpAddr() isCMsgProtoBufHeader_IpAddr {
	if x != nil {
		return x.IpAddr
	}
	return nil
}

func (x *CMsgProtoBufHeader) GetIp() uint32 {
	if x != nil {
		if x, ok := x.IpAddr.(*CMsgProtoBufHeader_Ip); ok {
			return x.Ip
		}
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetIpV6() []byte {
	if x != nil {
		if x, ok := x.IpAddr.(*CMsgProtoBufHeader_IpV6); ok {
			return x.IpV6
		}
	}
	return nil
}

type isCMsgProtoBufHeader_IpAddr interface {
	isCMsgProtoBufHeader_IpAddr()
}

type CMsgProtoBufHeader_Ip struct {
	Ip uint32 `protobuf:"varint,15,opt,name=ip,oneof"`
}

type CMsgProtoBufHeader_IpV6 struct {
	IpV6 []byte `protobuf:"bytes,29,opt,name=ip_v6,json=ipV6,oneof"`
}

func (*CMsgProtoBufHeader_Ip) isCMsgProtoBufHeader_IpAddr() {}

func (*CMsgProtoBufHeader_IpV6) isCMsgProtoBufHeader_IpAddr() {}

type CMsgMulti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeUnzipped  *uint32                `protobuf:"varint,1,opt,name=size_unzipped,json=sizeUnzipped" json:"size_unzipped,omitempty"`
	MessageBody   []byte                 `protobuf:"bytes,2,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgMulti) Reset() {
	*x = CMsgMulti{}
	mi := &file_steammessages_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgMulti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgMulti) ProtoMessage() {}

func (x *CMsgMulti) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgMulti.ProtoReflect.Descriptor instead.
func (*CMsgMulti) Descriptor() ([]byte, []int) {
	return file_steammessages_base_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgMulti) GetSizeUnzipped() uint32 {
	if x != nil && x.SizeUnzipped != nil {
		return *x.SizeUnzipped
	}
	return 0
}

func (x *CMsgMulti) GetMessageBody() []byte {
	if x != nil {
		return x.MessageBody
	}
	return nil
}

var file_steammessages_base_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50000,
		Name:          "msgpool_soft_limit",
		Tag:           "varint,50000,opt,name=msgpool_soft_limit,def=32",
		Filename:      "steammessages_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50001,
		Name:          "msgpool_hard_limit",
		Tag:           "varint,50001,opt,name=msgpool_hard_limit,def=384",
		Filename:      "steammessages_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50020,
		Name:          "php_output_always_number",
		Tag:           "varint,50020,opt,name=php_output_always_number,def=0",
		Filename:      "steammessages_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50024,
		Name:          "allow_field_named_steam_id",
		Tag:           "varint,50024,opt,name=allow_field_named_steam_id,def=0",
		Filename:      "steammessages_base.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional int32 msgpool_soft_limit = 50000;
	E_MsgpoolSoftLimit = &file_steammessages_base_proto_extTypes[0]
	// optional int32 msgpool_hard_limit = 50001;
	E_MsgpoolHardLimit = &file_steammessages_base_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool php_output_always_number = 50020;
	E_PhpOutputAlwaysNumber = &file_steammessages_base_proto_extTypes[2]
	// optional bool allow_field_named_steam_id = 50024;
	E_AllowFieldNamedSteamId = &file_steammessages_base_proto_extTypes[3]
)

var File_steammessages_base_proto protoreflect.FileDescriptor

const file_steammessages_base_proto_rawDesc = "" +
	"\n" +
	"\x18steammessages_base.proto\x1a google/protobuf/descriptor.proto\"9\n" +
	"\rCMsgIPAddress\x12\x10\n" +
	"\x02v4\x18\x01 \x01(\aH\x00R\x02v4\x12\x10\n" +
	"\x02v6\x18\x02 \x01(\fH\x00R\x02v6B\x04\n" +
	"\x02ip\"l\n" +
	"\x1bCMsgGCRoutingProtoBufHeader\x12$\n" +
	"\x0edst_gcid_queue\x18\x01 \x01(\x04R\fdstGcidQueue\x12'\n" +
	"\x10dst_gc_dir_index\x18\x02 \x01(\rR\rdstGcDirIndex\"\xd8\f\n" +
	"\x12CMsgProtoBufHeader\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12)\n" +
	"\x10client_sessionid\x18\x02 \x01(\x05R\x0fclientSessionid\x12#\n" +
	"\rrouting_appid\x18\x03 \x01(\rR\froutingAppid\x127\n" +
	"\fjobid_source\x18\n" +
	" \x01(\x06:\x1418446744073709551615R\vjobidSource\x127\n" +
	"\fjobid_target\x18\v \x01(\x06:\x1418446744073709551615R\vjobidTarget\x12&\n" +
	"\x0ftarget_job_name\x18\f \x01(\tR\rtargetJobName\x12\x17\n" +
	"\aseq_num\x18\x18 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\aeresult\x18\r \x01(\x05:\x012R\aeresult\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\x12,\n" +
	"\x12auth_account_flags\x18\x10 \x01(\rR\x10authAccountFlags\x12!\n" +
	"\ftoken_source\x18\x16 \x01(\rR\vtokenSource\x12.\n" +
	"\x13admin_spoofing_user\x18\x17 \x01(\bR\x11adminSpoofingUser\x12*\n" +
	"\x0ftransport_error\x18\x11 \x01(\x05:\x011R\x0etransportError\x122\n" +
	"\tmessageid\x18\x12 \x01(\x04:\x1418446744073709551615R\tmessageid\x12,\n" +
	"\x12publisher_group_id\x18\x13 \x01(\rR\x10publisherGroupId\x12\x14\n" +
	"\x05sysid\x18\x14 \x01(\rR\x05sysid\x12\"\n" +
	"\rwebapi_key_id\x18\x19 \x01(\rR\vwebapiKeyId\x125\n" +
	"\x17is_from_external_source\x18\x1a \x01(\bR\x14isFromExternalSource\x12(\n" +
	"\x10forward_to_sysid\x18\x1b \x03(\rR\x0eforwardToSysid\x12\x19\n" +
	"\bcm_sysid\x18\x1c \x01(\rR\acmSysid\x12&\n" +
	"\rlauncher_type\x18\x1f \x01(\r:\x010R\flauncherType\x12\x17\n" +
	"\x05realm\x18  \x01(\r:\x010R\x05realm\x12!\n" +
	"\n" +
	"timeout_ms\x18! \x01(\x05:\x02-1R\ttimeoutMs\x12!\n" +
	"\fdebug_source\x18\" \x01(\tR\vdebugSource\x129\n" +
	"\x19debug_source_string_index\x18# \x01(\rR\x16debugSourceStringIndex\x12\x19\n" +
	"\btoken_id\x18$ \x01(\x04R\atokenId\x12;\n" +
	"\n" +
	"routing_gc\x18% \x01(\v2\x1c.CMsgGCRoutingProtoBufHeaderR\troutingGc\x12u\n" +
	"\x13session_disposition\x18& \x01(\x0e2'.CMsgProtoBufHeader.ESessionDisposition:\x1bk_ESessionDispositionNormalR\x12sessionDisposition\x12\x19\n" +
	"\bwg_token\x18' \x01(\tR\awgToken\x12$\n" +
	"\x0ewebui_auth_key\x18( \x01(\tR\fwebuiAuthKey\x12:\n" +
	"\x19exclude_client_sessionids\x18) \x03(\x05R\x17excludeClientSessionids\x12C\n" +
	"\x1eadmin_request_spoofing_steamid\x18+ \x01(\x06R\x1badminRequestSpoofingSteamid\x12\x1d\n" +
	"\n" +
	"is_valveds\x18, \x01(\bR\tisValveds\x12\x1b\n" +
	"\ttrace_tag\x18- \x01(\x06R\btraceTag\x12\x10\n" +
	"\x02ip\x18\x0f \x01(\rH\x00R\x02ip\x12\x15\n" +
	"\x05ip_v6\x18\x1d \x01(\fH\x00R\x04ipV6\"[\n" +
	"\x13ESessionDisposition\x12\x1f\n" +
	"\x1bk_ESessionDispositionNormal\x10\x00\x12#\n" +
	"\x1fk_ESessionDispositionDisconnect\x10\x01B\t\n" +
	"\aip_addr\"S\n" +
	"\tCMsgMulti\x12#\n" +
	"\rsize_unzipped\x18\x01 \x01(\rR\fsizeUnzipped\x12!\n" +
	"\fmessage_body\x18\x02 \x01(\fR\vmessageBody:S\n" +
	"\x12msgpool_soft_limit\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\x05:\x0232R\x10msgpoolSoftLimit:T\n" +
	"\x12msgpool_hard_limit\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\x05:\x03384R\x10msgpoolHardLimit:_\n" +
	"\x18php_output_always_number\x12\x1d.google.protobuf.FieldOptions\x18\xe4\x86\x03 \x01(\b:\x05falseR\x15phpOutputAlwaysNumber:b\n" +
	"\x1aallow_field_named_steam_id\x12\x1d.google.protobuf.FieldOptions\x18\xe8\x86\x03 \x01(\b:\x05falseR\x16allowFieldNamedSteamIdB\x02H\x01"

var (
	file_steammessages_base_proto_rawDescOnce sync.Once
	file_steammessages_base_proto_rawDescData []byte
)

func file_steammessages_base_proto_rawDescGZIP() []byte {
	file_steammessages_base_proto_rawDescOnce.Do(func() {
		file_steammessages_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_base_proto_rawDesc), len(file_steammessages_base_proto_rawDesc)))
	})
	return file_steammessages_base_proto_rawDescData
}

var file_steammessages_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steammessages_base_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_steammessages_base_proto_goTypes = []any{
	(CMsgProtoBufHeader_ESessionDisposition)(0), // 0: CMsgProtoBufHeader.ESessionDisposition
	(*CMsgIPAddress)(nil),                       // 1: CMsgIPAddress
	(*CMsgGCRoutingProtoBufHeader)(nil),         // 2: CMsgGCRoutingProtoBufHeader
	(*CMsgProtoBufHeader)(nil),                  // 3: CMsgProtoBufHeader
	(*CMsgMulti)(nil),                           // 4: CMsgMulti
	(*descriptorpb.MessageOptions)(nil),         // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),           // 6: google.protobuf.FieldOptions
}
var file_steammessages_base_proto_depIdxs = []int32{
	2, // 0: CMsgProtoBufHeader.routing_gc:type_name -> CMsgGCRoutingProtoBufHeader
	0, // 1: CMsgProtoBufHeader.session_disposition:type_name -> CMsgProtoBufHeader.ESessionDisposition
	5, // 2: msgpool_soft_limit:extendee -> google.protobuf.MessageOptions
	5, // 3: msgpool_hard_limit:extendee -> google.protobuf.MessageOptions
	6, // 4: php_output_always_number:extendee -> google.protobuf.FieldOptions
	6, // 5: allow_field_named_steam_id:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	2, // [2:6] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_steammessages_base_proto_init() }
func file_steammessages_base_proto_init() {
	if File_steammessages_base_proto != nil {
		return
	}
	file_steammessages_base_proto_msgTypes[0].OneofWrappers = []any{
		(*CMsgIPAddress_V4)(nil),
		(*CMsgIPAddress_V6)(nil),
	}
	file_steammessages_base_proto_msgTypes[2].OneofWrappers = []any{
		(*CMsgProtoBufHeader_Ip)(nil),
		(*CMsgProtoBufHeader_IpV6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_base_proto_rawDesc), len(file_steammessages_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_base_proto_goTypes,
		DependencyIndexes: file_steammessages_base_proto_depIdxs,
		EnumInfos:         file_steammessages_base_proto_enumTypes,
		MessageInfos:      file_steammessages_base_proto_msgTypes,
		ExtensionInfos:    file_steammessages_base_proto_extTypes,
	}.Build()
	File_steammessages_base_proto = out.File
	file_steammessages_base_proto_goTypes = nil
	file_steammessages_base_proto_depIdxs = nil
}
