// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_unified_base.steamclient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EProtoExecutionSite int32

const (
	EProtoExecutionSite_k_EProtoExecutionSiteUnknown     EProtoExecutionSite = 0
	EProtoExecutionSite_k_EProtoExecutionSiteSteamClient EProtoExecutionSite = 2
)

// Enum value maps for EProtoExecutionSite.
var (
	EProtoExecutionSite_name = map[int32]string{
		0: "k_EProtoExecutionSiteUnknown",
		2: "k_EProtoExecutionSiteSteamClient",
	}
	EProtoExecutionSite_value = map[string]int32{
		"k_EProtoExecutionSiteUnknown":     0,
		"k_EProtoExecutionSiteSteamClient": 2,
	}
)

func (x EProtoExecutionSite) Enum() *EProtoExecutionSite {
	p := new(EProtoExecutionSite)
	*p = x
	return p
}

func (x EProtoExecutionSite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EProtoExecutionSite) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_unified_base_steamclient_proto_enumTypes[0].Descriptor()
}

func (EProtoExecutionSite) Type() protoreflect.EnumType {
	return &file_steammessages_unified_base_steamclient_proto_enumTypes[0]
}

func (x EProtoExecutionSite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EProtoExecutionSite) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EProtoExecutionSite(num)
	return nil
}

// Deprecated: Use EProtoExecutionSite.Descriptor instead.
func (EProtoExecutionSite) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_unified_base_steamclient_proto_rawDescGZIP(), []int{0}
}

type EProtoServiceType int32

const (
	EProtoServiceType_k_EProtoServiceTypeSteamMessages       EProtoServiceType = 0
	EProtoServiceType_k_EProtoServiceTypeVRGamepadUIMessages EProtoServiceType = 1
)

// Enum value maps for EProtoServiceType.
var (
	EProtoServiceType_name = map[int32]string{
		0: "k_EProtoServiceTypeSteamMessages",
		1: "k_EProtoServiceTypeVRGamepadUIMessages",
	}
	EProtoServiceType_value = map[string]int32{
		"k_EProtoServiceTypeSteamMessages":       0,
		"k_EProtoServiceTypeVRGamepadUIMessages": 1,
	}
)

func (x EProtoServiceType) Enum() *EProtoServiceType {
	p := new(EProtoServiceType)
	*p = x
	return p
}

func (x EProtoServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EProtoServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_unified_base_steamclient_proto_enumTypes[1].Descriptor()
}

func (EProtoServiceType) Type() protoreflect.EnumType {
	return &file_steammessages_unified_base_steamclient_proto_enumTypes[1]
}

func (x EProtoServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EProtoServiceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EProtoServiceType(num)
	return nil
}

// Deprecated: Use EProtoServiceType.Descriptor instead.
func (EProtoServiceType) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_unified_base_steamclient_proto_rawDescGZIP(), []int{1}
}

type NoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoResponse) Reset() {
	*x = NoResponse{}
	mi := &file_steammessages_unified_base_steamclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoResponse) ProtoMessage() {}

func (x *NoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_unified_base_steamclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoResponse.ProtoReflect.Descriptor instead.
func (*NoResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_unified_base_steamclient_proto_rawDescGZIP(), []int{0}
}

var file_steammessages_unified_base_steamclient_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51000,
		Name:          "message_description",
		Tag:           "bytes,51000,opt,name=message_description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50026,
		Name:          "force_emit_message",
		Tag:           "varint,50026,opt,name=force_emit_message,def=0",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "description",
		Tag:           "bytes,50000,opt,name=description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "service_description",
		Tag:           "bytes,50000,opt,name=service_description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*EProtoExecutionSite)(nil),
		Field:         50008,
		Name:          "service_execution_site",
		Tag:           "varint,50008,opt,name=service_execution_site,enum=EProtoExecutionSite,def=0",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*EProtoServiceType)(nil),
		Field:         50025,
		Name:          "service_type",
		Tag:           "varint,50025,opt,name=service_type,enum=EProtoServiceType,def=0",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50026,
		Name:          "force_emit_service",
		Tag:           "varint,50026,opt,name=force_emit_service,def=0",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "method_description",
		Tag:           "bytes,50000,opt,name=method_description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "enum_description",
		Tag:           "bytes,50000,opt,name=enum_description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "enum_value_description",
		Tag:           "bytes,50000,opt,name=enum_value_description",
		Filename:      "steammessages_unified_base.steamclient.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string message_description = 51000;
	E_MessageDescription = &file_steammessages_unified_base_steamclient_proto_extTypes[0]
	// optional bool force_emit_message = 50026;
	E_ForceEmitMessage = &file_steammessages_unified_base_steamclient_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string description = 50000;
	E_Description = &file_steammessages_unified_base_steamclient_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string service_description = 50000;
	E_ServiceDescription = &file_steammessages_unified_base_steamclient_proto_extTypes[3]
	// optional EProtoExecutionSite service_execution_site = 50008;
	E_ServiceExecutionSite = &file_steammessages_unified_base_steamclient_proto_extTypes[4]
	// optional EProtoServiceType service_type = 50025;
	E_ServiceType = &file_steammessages_unified_base_steamclient_proto_extTypes[5]
	// optional bool force_emit_service = 50026;
	E_ForceEmitService = &file_steammessages_unified_base_steamclient_proto_extTypes[6]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string method_description = 50000;
	E_MethodDescription = &file_steammessages_unified_base_steamclient_proto_extTypes[7]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional string enum_description = 50000;
	E_EnumDescription = &file_steammessages_unified_base_steamclient_proto_extTypes[8]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string enum_value_description = 50000;
	E_EnumValueDescription = &file_steammessages_unified_base_steamclient_proto_extTypes[9]
)

var File_steammessages_unified_base_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_unified_base_steamclient_proto_rawDesc = "" +
	"\n" +
	",steammessages_unified_base.steamclient.proto\x1a google/protobuf/descriptor.proto\"\f\n" +
	"\n" +
	"NoResponse*]\n" +
	"\x13EProtoExecutionSite\x12 \n" +
	"\x1ck_EProtoExecutionSiteUnknown\x10\x00\x12$\n" +
	" k_EProtoExecutionSiteSteamClient\x10\x02*e\n" +
	"\x11EProtoServiceType\x12$\n" +
	" k_EProtoServiceTypeSteamMessages\x10\x00\x12*\n" +
	"&k_EProtoServiceTypeVRGamepadUIMessages\x10\x01:R\n" +
	"\x13message_description\x12\x1f.google.protobuf.MessageOptions\x18\xb8\x8e\x03 \x01(\tR\x12messageDescription:V\n" +
	"\x12force_emit_message\x12\x1f.google.protobuf.MessageOptions\x18\xea\x86\x03 \x01(\b:\x05falseR\x10forceEmitMessage:A\n" +
	"\vdescription\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\tR\vdescription:R\n" +
	"\x13service_description\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\tR\x12serviceDescription:\x8b\x01\n" +
	"\x16service_execution_site\x12\x1f.google.protobuf.ServiceOptions\x18؆\x03 \x01(\x0e2\x14.EProtoExecutionSite:\x1ck_EProtoExecutionSiteUnknownR\x14serviceExecutionSite:z\n" +
	"\fservice_type\x12\x1f.google.protobuf.ServiceOptions\x18\xe9\x86\x03 \x01(\x0e2\x12.EProtoServiceType: k_EProtoServiceTypeSteamMessagesR\vserviceType:V\n" +
	"\x12force_emit_service\x12\x1f.google.protobuf.ServiceOptions\x18\xea\x86\x03 \x01(\b:\x05falseR\x10forceEmitService:O\n" +
	"\x12method_description\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\tR\x11methodDescription:I\n" +
	"\x10enum_description\x12\x1c.google.protobuf.EnumOptions\x18І\x03 \x01(\tR\x0fenumDescription:Y\n" +
	"\x16enum_value_description\x12!.google.protobuf.EnumValueOptions\x18І\x03 \x01(\tR\x14enumValueDescriptionB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_unified_base_steamclient_proto_rawDescOnce sync.Once
	file_steammessages_unified_base_steamclient_proto_rawDescData []byte
)

func file_steammessages_unified_base_steamclient_proto_rawDescGZIP() []byte {
	file_steammessages_unified_base_steamclient_proto_rawDescOnce.Do(func() {
		file_steammessages_unified_base_steamclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_unified_base_steamclient_proto_rawDesc), len(file_steammessages_unified_base_steamclient_proto_rawDesc)))
	})
	return file_steammessages_unified_base_steamclient_proto_rawDescData
}

var file_steammessages_unified_base_steamclient_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_steammessages_unified_base_steamclient_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_steammessages_unified_base_steamclient_proto_goTypes = []any{
	(EProtoExecutionSite)(0),              // 0: EProtoExecutionSite
	(EProtoServiceType)(0),                // 1: EProtoServiceType
	(*NoResponse)(nil),                    // 2: NoResponse
	(*descriptorpb.MessageOptions)(nil),   // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 4: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil),   // 5: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 6: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 7: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 8: google.protobuf.EnumValueOptions
}
var file_steammessages_unified_base_steamclient_proto_depIdxs = []int32{
	3,  // 0: message_description:extendee -> google.protobuf.MessageOptions
	3,  // 1: force_emit_message:extendee -> google.protobuf.MessageOptions
	4,  // 2: description:extendee -> google.protobuf.FieldOptions
	5,  // 3: service_description:extendee -> google.protobuf.ServiceOptions
	5,  // 4: service_execution_site:extendee -> google.protobuf.ServiceOptions
	5,  // 5: service_type:extendee -> google.protobuf.ServiceOptions
	5,  // 6: force_emit_service:extendee -> google.protobuf.ServiceOptions
	6,  // 7: method_description:extendee -> google.protobuf.MethodOptions
	7,  // 8: enum_description:extendee -> google.protobuf.EnumOptions
	8,  // 9: enum_value_description:extendee -> google.protobuf.EnumValueOptions
	0,  // 10: service_execution_site:type_name -> EProtoExecutionSite
	1,  // 11: service_type:type_name -> EProtoServiceType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	10, // [10:12] is the sub-list for extension type_name
	0,  // [0:10] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_unified_base_steamclient_proto_init() }
func file_steammessages_unified_base_steamclient_proto_init() {
	if File_steammessages_unified_base_steamclient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_unified_base_steamclient_proto_rawDesc), len(file_steammessages_unified_base_steamclient_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_unified_base_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_unified_base_steamclient_proto_depIdxs,
		EnumInfos:         file_steammessages_unified_base_steamclient_proto_enumTypes,
		MessageInfos:      file_steammessages_unified_base_steamclient_proto_msgTypes,
		ExtensionInfos:    file_steammessages_unified_base_steamclient_proto_extTypes,
	}.Build()
	File_steammessages_unified_base_steamclient_proto = out.File
	file_steammessages_unified_base_steamclient_proto_goTypes = nil
	file_steammessages_unified_base_steamclient_proto_depIdxs = nil
}
