// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_clientserver_appinfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientAppInfoUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastChangenumber *uint32                `protobuf:"varint,1,opt,name=last_changenumber,json=lastChangenumber" json:"last_changenumber,omitempty"`
	SendChangelist   *bool                  `protobuf:"varint,2,opt,name=send_changelist,json=sendChangelist" json:"send_changelist,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CMsgClientAppInfoUpdate) Reset() {
	*x = CMsgClientAppInfoUpdate{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientAppInfoUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientAppInfoUpdate) ProtoMessage() {}

func (x *CMsgClientAppInfoUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientAppInfoUpdate.ProtoReflect.Descriptor instead.
func (*CMsgClientAppInfoUpdate) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientAppInfoUpdate) GetLastChangenumber() uint32 {
	if x != nil && x.LastChangenumber != nil {
		return *x.LastChangenumber
	}
	return 0
}

func (x *CMsgClientAppInfoUpdate) GetSendChangelist() bool {
	if x != nil && x.SendChangelist != nil {
		return *x.SendChangelist
	}
	return false
}

type CMsgClientAppInfoChanges struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentChangeNumber *uint32                `protobuf:"varint,1,opt,name=current_change_number,json=currentChangeNumber" json:"current_change_number,omitempty"`
	ForceFullUpdate     *bool                  `protobuf:"varint,2,opt,name=force_full_update,json=forceFullUpdate" json:"force_full_update,omitempty"`
	AppIDs              []uint32               `protobuf:"varint,3,rep,name=appIDs" json:"appIDs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMsgClientAppInfoChanges) Reset() {
	*x = CMsgClientAppInfoChanges{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientAppInfoChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientAppInfoChanges) ProtoMessage() {}

func (x *CMsgClientAppInfoChanges) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientAppInfoChanges.ProtoReflect.Descriptor instead.
func (*CMsgClientAppInfoChanges) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientAppInfoChanges) GetCurrentChangeNumber() uint32 {
	if x != nil && x.CurrentChangeNumber != nil {
		return *x.CurrentChangeNumber
	}
	return 0
}

func (x *CMsgClientAppInfoChanges) GetForceFullUpdate() bool {
	if x != nil && x.ForceFullUpdate != nil {
		return *x.ForceFullUpdate
	}
	return false
}

func (x *CMsgClientAppInfoChanges) GetAppIDs() []uint32 {
	if x != nil {
		return x.AppIDs
	}
	return nil
}

type CMsgClientAppInfoRequest struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	Apps            []*CMsgClientAppInfoRequest_App `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	SupportsBatches *bool                           `protobuf:"varint,2,opt,name=supports_batches,json=supportsBatches,def=0" json:"supports_batches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for CMsgClientAppInfoRequest fields.
const (
	Default_CMsgClientAppInfoRequest_SupportsBatches = bool(false)
)

func (x *CMsgClientAppInfoRequest) Reset() {
	*x = CMsgClientAppInfoRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientAppInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientAppInfoRequest) ProtoMessage() {}

func (x *CMsgClientAppInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientAppInfoRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientAppInfoRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientAppInfoRequest) GetApps() []*CMsgClientAppInfoRequest_App {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CMsgClientAppInfoRequest) GetSupportsBatches() bool {
	if x != nil && x.SupportsBatches != nil {
		return *x.SupportsBatches
	}
	return Default_CMsgClientAppInfoRequest_SupportsBatches
}

type CMsgClientPICSChangesSinceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SinceChangeNumber      *uint32                `protobuf:"varint,1,opt,name=since_change_number,json=sinceChangeNumber" json:"since_change_number,omitempty"`
	SendAppInfoChanges     *bool                  `protobuf:"varint,2,opt,name=send_app_info_changes,json=sendAppInfoChanges" json:"send_app_info_changes,omitempty"`
	SendPackageInfoChanges *bool                  `protobuf:"varint,3,opt,name=send_package_info_changes,json=sendPackageInfoChanges" json:"send_package_info_changes,omitempty"`
	NumAppInfoCached       *uint32                `protobuf:"varint,4,opt,name=num_app_info_cached,json=numAppInfoCached" json:"num_app_info_cached,omitempty"`
	NumPackageInfoCached   *uint32                `protobuf:"varint,5,opt,name=num_package_info_cached,json=numPackageInfoCached" json:"num_package_info_cached,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CMsgClientPICSChangesSinceRequest) Reset() {
	*x = CMsgClientPICSChangesSinceRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSChangesSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSChangesSinceRequest) ProtoMessage() {}

func (x *CMsgClientPICSChangesSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSChangesSinceRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSChangesSinceRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientPICSChangesSinceRequest) GetSinceChangeNumber() uint32 {
	if x != nil && x.SinceChangeNumber != nil {
		return *x.SinceChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceRequest) GetSendAppInfoChanges() bool {
	if x != nil && x.SendAppInfoChanges != nil {
		return *x.SendAppInfoChanges
	}
	return false
}

func (x *CMsgClientPICSChangesSinceRequest) GetSendPackageInfoChanges() bool {
	if x != nil && x.SendPackageInfoChanges != nil {
		return *x.SendPackageInfoChanges
	}
	return false
}

func (x *CMsgClientPICSChangesSinceRequest) GetNumAppInfoCached() uint32 {
	if x != nil && x.NumAppInfoCached != nil {
		return *x.NumAppInfoCached
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceRequest) GetNumPackageInfoCached() uint32 {
	if x != nil && x.NumPackageInfoCached != nil {
		return *x.NumPackageInfoCached
	}
	return 0
}

type CMsgClientPICSChangesSinceResponse struct {
	state                  protoimpl.MessageState                              `protogen:"open.v1"`
	CurrentChangeNumber    *uint32                                             `protobuf:"varint,1,opt,name=current_change_number,json=currentChangeNumber" json:"current_change_number,omitempty"`
	SinceChangeNumber      *uint32                                             `protobuf:"varint,2,opt,name=since_change_number,json=sinceChangeNumber" json:"since_change_number,omitempty"`
	ForceFullUpdate        *bool                                               `protobuf:"varint,3,opt,name=force_full_update,json=forceFullUpdate" json:"force_full_update,omitempty"`
	PackageChanges         []*CMsgClientPICSChangesSinceResponse_PackageChange `protobuf:"bytes,4,rep,name=package_changes,json=packageChanges" json:"package_changes,omitempty"`
	AppChanges             []*CMsgClientPICSChangesSinceResponse_AppChange     `protobuf:"bytes,5,rep,name=app_changes,json=appChanges" json:"app_changes,omitempty"`
	ForceFullAppUpdate     *bool                                               `protobuf:"varint,6,opt,name=force_full_app_update,json=forceFullAppUpdate" json:"force_full_app_update,omitempty"`
	ForceFullPackageUpdate *bool                                               `protobuf:"varint,7,opt,name=force_full_package_update,json=forceFullPackageUpdate" json:"force_full_package_update,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CMsgClientPICSChangesSinceResponse) Reset() {
	*x = CMsgClientPICSChangesSinceResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSChangesSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSChangesSinceResponse) ProtoMessage() {}

func (x *CMsgClientPICSChangesSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSChangesSinceResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSChangesSinceResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgClientPICSChangesSinceResponse) GetCurrentChangeNumber() uint32 {
	if x != nil && x.CurrentChangeNumber != nil {
		return *x.CurrentChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse) GetSinceChangeNumber() uint32 {
	if x != nil && x.SinceChangeNumber != nil {
		return *x.SinceChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse) GetForceFullUpdate() bool {
	if x != nil && x.ForceFullUpdate != nil {
		return *x.ForceFullUpdate
	}
	return false
}

func (x *CMsgClientPICSChangesSinceResponse) GetPackageChanges() []*CMsgClientPICSChangesSinceResponse_PackageChange {
	if x != nil {
		return x.PackageChanges
	}
	return nil
}

func (x *CMsgClientPICSChangesSinceResponse) GetAppChanges() []*CMsgClientPICSChangesSinceResponse_AppChange {
	if x != nil {
		return x.AppChanges
	}
	return nil
}

func (x *CMsgClientPICSChangesSinceResponse) GetForceFullAppUpdate() bool {
	if x != nil && x.ForceFullAppUpdate != nil {
		return *x.ForceFullAppUpdate
	}
	return false
}

func (x *CMsgClientPICSChangesSinceResponse) GetForceFullPackageUpdate() bool {
	if x != nil && x.ForceFullPackageUpdate != nil {
		return *x.ForceFullPackageUpdate
	}
	return false
}

type CMsgClientPICSProductInfoRequest struct {
	state                         protoimpl.MessageState                          `protogen:"open.v1"`
	Packages                      []*CMsgClientPICSProductInfoRequest_PackageInfo `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
	Apps                          []*CMsgClientPICSProductInfoRequest_AppInfo     `protobuf:"bytes,2,rep,name=apps" json:"apps,omitempty"`
	MetaDataOnly                  *bool                                           `protobuf:"varint,3,opt,name=meta_data_only,json=metaDataOnly" json:"meta_data_only,omitempty"`
	NumPrevFailed                 *uint32                                         `protobuf:"varint,4,opt,name=num_prev_failed,json=numPrevFailed" json:"num_prev_failed,omitempty"`
	OBSOLETESupportsPackageTokens *uint32                                         `protobuf:"varint,5,opt,name=OBSOLETE_supports_package_tokens,json=OBSOLETESupportsPackageTokens" json:"OBSOLETE_supports_package_tokens,omitempty"`
	SequenceNumber                *uint32                                         `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	SingleResponse                *bool                                           `protobuf:"varint,7,opt,name=single_response,json=singleResponse" json:"single_response,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest) Reset() {
	*x = CMsgClientPICSProductInfoRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgClientPICSProductInfoRequest) GetPackages() []*CMsgClientPICSProductInfoRequest_PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CMsgClientPICSProductInfoRequest) GetApps() []*CMsgClientPICSProductInfoRequest_AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CMsgClientPICSProductInfoRequest) GetMetaDataOnly() bool {
	if x != nil && x.MetaDataOnly != nil {
		return *x.MetaDataOnly
	}
	return false
}

func (x *CMsgClientPICSProductInfoRequest) GetNumPrevFailed() uint32 {
	if x != nil && x.NumPrevFailed != nil {
		return *x.NumPrevFailed
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetOBSOLETESupportsPackageTokens() uint32 {
	if x != nil && x.OBSOLETESupportsPackageTokens != nil {
		return *x.OBSOLETESupportsPackageTokens
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetSequenceNumber() uint32 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetSingleResponse() bool {
	if x != nil && x.SingleResponse != nil {
		return *x.SingleResponse
	}
	return false
}

type CMsgClientPICSProductInfoResponse struct {
	state             protoimpl.MessageState                           `protogen:"open.v1"`
	Apps              []*CMsgClientPICSProductInfoResponse_AppInfo     `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	UnknownAppids     []uint32                                         `protobuf:"varint,2,rep,name=unknown_appids,json=unknownAppids" json:"unknown_appids,omitempty"`
	Packages          []*CMsgClientPICSProductInfoResponse_PackageInfo `protobuf:"bytes,3,rep,name=packages" json:"packages,omitempty"`
	UnknownPackageids []uint32                                         `protobuf:"varint,4,rep,name=unknown_packageids,json=unknownPackageids" json:"unknown_packageids,omitempty"`
	MetaDataOnly      *bool                                            `protobuf:"varint,5,opt,name=meta_data_only,json=metaDataOnly" json:"meta_data_only,omitempty"`
	ResponsePending   *bool                                            `protobuf:"varint,6,opt,name=response_pending,json=responsePending" json:"response_pending,omitempty"`
	HttpMinSize       *uint32                                          `protobuf:"varint,7,opt,name=http_min_size,json=httpMinSize" json:"http_min_size,omitempty"`
	HttpHost          *string                                          `protobuf:"bytes,8,opt,name=http_host,json=httpHost" json:"http_host,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse) Reset() {
	*x = CMsgClientPICSProductInfoResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{6}
}

func (x *CMsgClientPICSProductInfoResponse) GetApps() []*CMsgClientPICSProductInfoResponse_AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetUnknownAppids() []uint32 {
	if x != nil {
		return x.UnknownAppids
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetPackages() []*CMsgClientPICSProductInfoResponse_PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetUnknownPackageids() []uint32 {
	if x != nil {
		return x.UnknownPackageids
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetMetaDataOnly() bool {
	if x != nil && x.MetaDataOnly != nil {
		return *x.MetaDataOnly
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse) GetResponsePending() bool {
	if x != nil && x.ResponsePending != nil {
		return *x.ResponsePending
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse) GetHttpMinSize() uint32 {
	if x != nil && x.HttpMinSize != nil {
		return *x.HttpMinSize
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse) GetHttpHost() string {
	if x != nil && x.HttpHost != nil {
		return *x.HttpHost
	}
	return ""
}

type CMsgClientPICSAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageids    []uint32               `protobuf:"varint,1,rep,name=packageids" json:"packageids,omitempty"`
	Appids        []uint32               `protobuf:"varint,2,rep,name=appids" json:"appids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenRequest) Reset() {
	*x = CMsgClientPICSAccessTokenRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenRequest) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{7}
}

func (x *CMsgClientPICSAccessTokenRequest) GetPackageids() []uint32 {
	if x != nil {
		return x.Packageids
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenRequest) GetAppids() []uint32 {
	if x != nil {
		return x.Appids
	}
	return nil
}

type CMsgClientPICSAccessTokenResponse struct {
	state               protoimpl.MessageState                            `protogen:"open.v1"`
	PackageAccessTokens []*CMsgClientPICSAccessTokenResponse_PackageToken `protobuf:"bytes,1,rep,name=package_access_tokens,json=packageAccessTokens" json:"package_access_tokens,omitempty"`
	PackageDeniedTokens []uint32                                          `protobuf:"varint,2,rep,name=package_denied_tokens,json=packageDeniedTokens" json:"package_denied_tokens,omitempty"`
	AppAccessTokens     []*CMsgClientPICSAccessTokenResponse_AppToken     `protobuf:"bytes,3,rep,name=app_access_tokens,json=appAccessTokens" json:"app_access_tokens,omitempty"`
	AppDeniedTokens     []uint32                                          `protobuf:"varint,4,rep,name=app_denied_tokens,json=appDeniedTokens" json:"app_denied_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse) Reset() {
	*x = CMsgClientPICSAccessTokenResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{8}
}

func (x *CMsgClientPICSAccessTokenResponse) GetPackageAccessTokens() []*CMsgClientPICSAccessTokenResponse_PackageToken {
	if x != nil {
		return x.PackageAccessTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetPackageDeniedTokens() []uint32 {
	if x != nil {
		return x.PackageDeniedTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetAppAccessTokens() []*CMsgClientPICSAccessTokenResponse_AppToken {
	if x != nil {
		return x.AppAccessTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetAppDeniedTokens() []uint32 {
	if x != nil {
		return x.AppDeniedTokens
	}
	return nil
}

type CMsgClientPICSPrivateBetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	BetaName      *string                `protobuf:"bytes,3,opt,name=beta_name,json=betaName" json:"beta_name,omitempty"`
	PasswordHash  []byte                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSPrivateBetaRequest) Reset() {
	*x = CMsgClientPICSPrivateBetaRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSPrivateBetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSPrivateBetaRequest) ProtoMessage() {}

func (x *CMsgClientPICSPrivateBetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSPrivateBetaRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSPrivateBetaRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{9}
}

func (x *CMsgClientPICSPrivateBetaRequest) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSPrivateBetaRequest) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

func (x *CMsgClientPICSPrivateBetaRequest) GetBetaName() string {
	if x != nil && x.BetaName != nil {
		return *x.BetaName
	}
	return ""
}

func (x *CMsgClientPICSPrivateBetaRequest) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

type CMsgClientPICSPrivateBetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eresult       *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DepotSection  []byte                 `protobuf:"bytes,2,opt,name=depot_section,json=depotSection" json:"depot_section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientPICSPrivateBetaResponse fields.
const (
	Default_CMsgClientPICSPrivateBetaResponse_Eresult = int32(2)
)

func (x *CMsgClientPICSPrivateBetaResponse) Reset() {
	*x = CMsgClientPICSPrivateBetaResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSPrivateBetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSPrivateBetaResponse) ProtoMessage() {}

func (x *CMsgClientPICSPrivateBetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSPrivateBetaResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSPrivateBetaResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{10}
}

func (x *CMsgClientPICSPrivateBetaResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientPICSPrivateBetaResponse_Eresult
}

func (x *CMsgClientPICSPrivateBetaResponse) GetDepotSection() []byte {
	if x != nil {
		return x.DepotSection
	}
	return nil
}

type CMsgClientAppInfoRequest_App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	SectionFlags  *uint32                `protobuf:"varint,2,opt,name=section_flags,json=sectionFlags" json:"section_flags,omitempty"`
	Section_CRC   []uint32               `protobuf:"varint,3,rep,name=section_CRC,json=sectionCRC" json:"section_CRC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientAppInfoRequest_App) Reset() {
	*x = CMsgClientAppInfoRequest_App{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientAppInfoRequest_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientAppInfoRequest_App) ProtoMessage() {}

func (x *CMsgClientAppInfoRequest_App) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientAppInfoRequest_App.ProtoReflect.Descriptor instead.
func (*CMsgClientAppInfoRequest_App) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CMsgClientAppInfoRequest_App) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientAppInfoRequest_App) GetSectionFlags() uint32 {
	if x != nil && x.SectionFlags != nil {
		return *x.SectionFlags
	}
	return 0
}

func (x *CMsgClientAppInfoRequest_App) GetSection_CRC() []uint32 {
	if x != nil {
		return x.Section_CRC
	}
	return nil
}

type CMsgClientPICSChangesSinceResponse_PackageChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	NeedsToken    *bool                  `protobuf:"varint,3,opt,name=needs_token,json=needsToken" json:"needs_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) Reset() {
	*x = CMsgClientPICSChangesSinceResponse_PackageChange{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSChangesSinceResponse_PackageChange) ProtoMessage() {}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSChangesSinceResponse_PackageChange.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSChangesSinceResponse_PackageChange) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse_PackageChange) GetNeedsToken() bool {
	if x != nil && x.NeedsToken != nil {
		return *x.NeedsToken
	}
	return false
}

type CMsgClientPICSChangesSinceResponse_AppChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	NeedsToken    *bool                  `protobuf:"varint,3,opt,name=needs_token,json=needsToken" json:"needs_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) Reset() {
	*x = CMsgClientPICSChangesSinceResponse_AppChange{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSChangesSinceResponse_AppChange) ProtoMessage() {}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSChangesSinceResponse_AppChange.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSChangesSinceResponse_AppChange) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{4, 1}
}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSChangesSinceResponse_AppChange) GetNeedsToken() bool {
	if x != nil && x.NeedsToken != nil {
		return *x.NeedsToken
	}
	return false
}

type CMsgClientPICSProductInfoRequest_AppInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Appid              *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AccessToken        *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	OnlyPublicObsolete *bool                  `protobuf:"varint,3,opt,name=only_public_obsolete,json=onlyPublicObsolete" json:"only_public_obsolete,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) Reset() {
	*x = CMsgClientPICSProductInfoRequest_AppInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest_AppInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest_AppInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest_AppInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetOnlyPublicObsolete() bool {
	if x != nil && x.OnlyPublicObsolete != nil {
		return *x.OnlyPublicObsolete
	}
	return false
}

type CMsgClientPICSProductInfoRequest_PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) Reset() {
	*x = CMsgClientPICSProductInfoRequest_PackageInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest_PackageInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest_PackageInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest_PackageInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{5, 1}
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

type CMsgClientPICSProductInfoResponse_AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	MissingToken  *bool                  `protobuf:"varint,3,opt,name=missing_token,json=missingToken" json:"missing_token,omitempty"`
	Sha           []byte                 `protobuf:"bytes,4,opt,name=sha" json:"sha,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,5,opt,name=buffer" json:"buffer,omitempty"`
	OnlyPublic    *bool                  `protobuf:"varint,6,opt,name=only_public,json=onlyPublic" json:"only_public,omitempty"`
	Size          *uint32                `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) Reset() {
	*x = CMsgClientPICSProductInfoResponse_AppInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse_AppInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse_AppInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse_AppInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetMissingToken() bool {
	if x != nil && x.MissingToken != nil {
		return *x.MissingToken
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetSha() []byte {
	if x != nil {
		return x.Sha
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetOnlyPublic() bool {
	if x != nil && x.OnlyPublic != nil {
		return *x.OnlyPublic
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type CMsgClientPICSProductInfoResponse_PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	MissingToken  *bool                  `protobuf:"varint,3,opt,name=missing_token,json=missingToken" json:"missing_token,omitempty"`
	Sha           []byte                 `protobuf:"bytes,4,opt,name=sha" json:"sha,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,5,opt,name=buffer" json:"buffer,omitempty"`
	Size          *uint32                `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) Reset() {
	*x = CMsgClientPICSProductInfoResponse_PackageInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse_PackageInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse_PackageInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse_PackageInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetMissingToken() bool {
	if x != nil && x.MissingToken != nil {
		return *x.MissingToken
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetSha() []byte {
	if x != nil {
		return x.Sha
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type CMsgClientPICSAccessTokenResponse_PackageToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) Reset() {
	*x = CMsgClientPICSAccessTokenResponse_PackageToken{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse_PackageToken) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse_PackageToken.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse_PackageToken) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

type CMsgClientPICSAccessTokenResponse_AppToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) Reset() {
	*x = CMsgClientPICSAccessTokenResponse_AppToken{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse_AppToken) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse_AppToken.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse_AppToken) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

var File_steammessages_clientserver_appinfo_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_appinfo_proto_rawDesc = "" +
	"\n" +
	"(steammessages_clientserver_appinfo.proto\x1a\x18steammessages_base.proto\"o\n" +
	"\x17CMsgClientAppInfoUpdate\x12+\n" +
	"\x11last_changenumber\x18\x01 \x01(\rR\x10lastChangenumber\x12'\n" +
	"\x0fsend_changelist\x18\x02 \x01(\bR\x0esendChangelist\"\x92\x01\n" +
	"\x18CMsgClientAppInfoChanges\x122\n" +
	"\x15current_change_number\x18\x01 \x01(\rR\x13currentChangeNumber\x12*\n" +
	"\x11force_full_update\x18\x02 \x01(\bR\x0fforceFullUpdate\x12\x16\n" +
	"\x06appIDs\x18\x03 \x03(\rR\x06appIDs\"\xe3\x01\n" +
	"\x18CMsgClientAppInfoRequest\x121\n" +
	"\x04apps\x18\x01 \x03(\v2\x1d.CMsgClientAppInfoRequest.AppR\x04apps\x120\n" +
	"\x10supports_batches\x18\x02 \x01(\b:\x05falseR\x0fsupportsBatches\x1ab\n" +
	"\x03App\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12#\n" +
	"\rsection_flags\x18\x02 \x01(\rR\fsectionFlags\x12\x1f\n" +
	"\vsection_CRC\x18\x03 \x03(\rR\n" +
	"sectionCRC\"\xa7\x02\n" +
	"!CMsgClientPICSChangesSinceRequest\x12.\n" +
	"\x13since_change_number\x18\x01 \x01(\rR\x11sinceChangeNumber\x121\n" +
	"\x15send_app_info_changes\x18\x02 \x01(\bR\x12sendAppInfoChanges\x129\n" +
	"\x19send_package_info_changes\x18\x03 \x01(\bR\x16sendPackageInfoChanges\x12-\n" +
	"\x13num_app_info_cached\x18\x04 \x01(\rR\x10numAppInfoCached\x125\n" +
	"\x17num_package_info_cached\x18\x05 \x01(\rR\x14numPackageInfoCached\"\xac\x05\n" +
	"\"CMsgClientPICSChangesSinceResponse\x122\n" +
	"\x15current_change_number\x18\x01 \x01(\rR\x13currentChangeNumber\x12.\n" +
	"\x13since_change_number\x18\x02 \x01(\rR\x11sinceChangeNumber\x12*\n" +
	"\x11force_full_update\x18\x03 \x01(\bR\x0fforceFullUpdate\x12Z\n" +
	"\x0fpackage_changes\x18\x04 \x03(\v21.CMsgClientPICSChangesSinceResponse.PackageChangeR\x0epackageChanges\x12N\n" +
	"\vapp_changes\x18\x05 \x03(\v2-.CMsgClientPICSChangesSinceResponse.AppChangeR\n" +
	"appChanges\x121\n" +
	"\x15force_full_app_update\x18\x06 \x01(\bR\x12forceFullAppUpdate\x129\n" +
	"\x19force_full_package_update\x18\a \x01(\bR\x16forceFullPackageUpdate\x1as\n" +
	"\rPackageChange\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12\x1f\n" +
	"\vneeds_token\x18\x03 \x01(\bR\n" +
	"needsToken\x1ag\n" +
	"\tAppChange\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12\x1f\n" +
	"\vneeds_token\x18\x03 \x01(\bR\n" +
	"needsToken\"\xdb\x04\n" +
	" CMsgClientPICSProductInfoRequest\x12I\n" +
	"\bpackages\x18\x01 \x03(\v2-.CMsgClientPICSProductInfoRequest.PackageInfoR\bpackages\x12=\n" +
	"\x04apps\x18\x02 \x03(\v2).CMsgClientPICSProductInfoRequest.AppInfoR\x04apps\x12$\n" +
	"\x0emeta_data_only\x18\x03 \x01(\bR\fmetaDataOnly\x12&\n" +
	"\x0fnum_prev_failed\x18\x04 \x01(\rR\rnumPrevFailed\x12G\n" +
	" OBSOLETE_supports_package_tokens\x18\x05 \x01(\rR\x1dOBSOLETESupportsPackageTokens\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\rR\x0esequenceNumber\x12'\n" +
	"\x0fsingle_response\x18\a \x01(\bR\x0esingleResponse\x1at\n" +
	"\aAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\x120\n" +
	"\x14only_public_obsolete\x18\x03 \x01(\bR\x12onlyPublicObsolete\x1aN\n" +
	"\vPackageInfo\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\"\x9e\x06\n" +
	"!CMsgClientPICSProductInfoResponse\x12>\n" +
	"\x04apps\x18\x01 \x03(\v2*.CMsgClientPICSProductInfoResponse.AppInfoR\x04apps\x12%\n" +
	"\x0eunknown_appids\x18\x02 \x03(\rR\runknownAppids\x12J\n" +
	"\bpackages\x18\x03 \x03(\v2..CMsgClientPICSProductInfoResponse.PackageInfoR\bpackages\x12-\n" +
	"\x12unknown_packageids\x18\x04 \x03(\rR\x11unknownPackageids\x12$\n" +
	"\x0emeta_data_only\x18\x05 \x01(\bR\fmetaDataOnly\x12)\n" +
	"\x10response_pending\x18\x06 \x01(\bR\x0fresponsePending\x12\"\n" +
	"\rhttp_min_size\x18\a \x01(\rR\vhttpMinSize\x12\x1b\n" +
	"\thttp_host\x18\b \x01(\tR\bhttpHost\x1a\xc8\x01\n" +
	"\aAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12#\n" +
	"\rmissing_token\x18\x03 \x01(\bR\fmissingToken\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\fR\x03sha\x12\x16\n" +
	"\x06buffer\x18\x05 \x01(\fR\x06buffer\x12\x1f\n" +
	"\vonly_public\x18\x06 \x01(\bR\n" +
	"onlyPublic\x12\x12\n" +
	"\x04size\x18\a \x01(\rR\x04size\x1a\xb3\x01\n" +
	"\vPackageInfo\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12#\n" +
	"\rmissing_token\x18\x03 \x01(\bR\fmissingToken\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\fR\x03sha\x12\x16\n" +
	"\x06buffer\x18\x05 \x01(\fR\x06buffer\x12\x12\n" +
	"\x04size\x18\x06 \x01(\rR\x04size:\x04\x88\xb5\x18\x00\"Z\n" +
	" CMsgClientPICSAccessTokenRequest\x12\x1e\n" +
	"\n" +
	"packageids\x18\x01 \x03(\rR\n" +
	"packageids\x12\x16\n" +
	"\x06appids\x18\x02 \x03(\rR\x06appids\"\xd7\x03\n" +
	"!CMsgClientPICSAccessTokenResponse\x12c\n" +
	"\x15package_access_tokens\x18\x01 \x03(\v2/.CMsgClientPICSAccessTokenResponse.PackageTokenR\x13packageAccessTokens\x122\n" +
	"\x15package_denied_tokens\x18\x02 \x03(\rR\x13packageDeniedTokens\x12W\n" +
	"\x11app_access_tokens\x18\x03 \x03(\v2+.CMsgClientPICSAccessTokenResponse.AppTokenR\x0fappAccessTokens\x12*\n" +
	"\x11app_denied_tokens\x18\x04 \x03(\rR\x0fappDeniedTokens\x1aO\n" +
	"\fPackageToken\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\x1aC\n" +
	"\bAppToken\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\"\x9d\x01\n" +
	" CMsgClientPICSPrivateBetaRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\x12\x1b\n" +
	"\tbeta_name\x18\x03 \x01(\tR\bbetaName\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\fR\fpasswordHash\"e\n" +
	"!CMsgClientPICSPrivateBetaResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12#\n" +
	"\rdepot_section\x18\x02 \x01(\fR\fdepotSectionB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_appinfo_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_appinfo_proto_rawDescData []byte
)

func file_steammessages_clientserver_appinfo_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_appinfo_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_appinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_appinfo_proto_rawDesc), len(file_steammessages_clientserver_appinfo_proto_rawDesc)))
	})
	return file_steammessages_clientserver_appinfo_proto_rawDescData
}

var file_steammessages_clientserver_appinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_steammessages_clientserver_appinfo_proto_goTypes = []any{
	(*CMsgClientAppInfoUpdate)(nil),                          // 0: CMsgClientAppInfoUpdate
	(*CMsgClientAppInfoChanges)(nil),                         // 1: CMsgClientAppInfoChanges
	(*CMsgClientAppInfoRequest)(nil),                         // 2: CMsgClientAppInfoRequest
	(*CMsgClientPICSChangesSinceRequest)(nil),                // 3: CMsgClientPICSChangesSinceRequest
	(*CMsgClientPICSChangesSinceResponse)(nil),               // 4: CMsgClientPICSChangesSinceResponse
	(*CMsgClientPICSProductInfoRequest)(nil),                 // 5: CMsgClientPICSProductInfoRequest
	(*CMsgClientPICSProductInfoResponse)(nil),                // 6: CMsgClientPICSProductInfoResponse
	(*CMsgClientPICSAccessTokenRequest)(nil),                 // 7: CMsgClientPICSAccessTokenRequest
	(*CMsgClientPICSAccessTokenResponse)(nil),                // 8: CMsgClientPICSAccessTokenResponse
	(*CMsgClientPICSPrivateBetaRequest)(nil),                 // 9: CMsgClientPICSPrivateBetaRequest
	(*CMsgClientPICSPrivateBetaResponse)(nil),                // 10: CMsgClientPICSPrivateBetaResponse
	(*CMsgClientAppInfoRequest_App)(nil),                     // 11: CMsgClientAppInfoRequest.App
	(*CMsgClientPICSChangesSinceResponse_PackageChange)(nil), // 12: CMsgClientPICSChangesSinceResponse.PackageChange
	(*CMsgClientPICSChangesSinceResponse_AppChange)(nil),     // 13: CMsgClientPICSChangesSinceResponse.AppChange
	(*CMsgClientPICSProductInfoRequest_AppInfo)(nil),         // 14: CMsgClientPICSProductInfoRequest.AppInfo
	(*CMsgClientPICSProductInfoRequest_PackageInfo)(nil),     // 15: CMsgClientPICSProductInfoRequest.PackageInfo
	(*CMsgClientPICSProductInfoResponse_AppInfo)(nil),        // 16: CMsgClientPICSProductInfoResponse.AppInfo
	(*CMsgClientPICSProductInfoResponse_PackageInfo)(nil),    // 17: CMsgClientPICSProductInfoResponse.PackageInfo
	(*CMsgClientPICSAccessTokenResponse_PackageToken)(nil),   // 18: CMsgClientPICSAccessTokenResponse.PackageToken
	(*CMsgClientPICSAccessTokenResponse_AppToken)(nil),       // 19: CMsgClientPICSAccessTokenResponse.AppToken
}
var file_steammessages_clientserver_appinfo_proto_depIdxs = []int32{
	11, // 0: CMsgClientAppInfoRequest.apps:type_name -> CMsgClientAppInfoRequest.App
	12, // 1: CMsgClientPICSChangesSinceResponse.package_changes:type_name -> CMsgClientPICSChangesSinceResponse.PackageChange
	13, // 2: CMsgClientPICSChangesSinceResponse.app_changes:type_name -> CMsgClientPICSChangesSinceResponse.AppChange
	15, // 3: CMsgClientPICSProductInfoRequest.packages:type_name -> CMsgClientPICSProductInfoRequest.PackageInfo
	14, // 4: CMsgClientPICSProductInfoRequest.apps:type_name -> CMsgClientPICSProductInfoRequest.AppInfo
	16, // 5: CMsgClientPICSProductInfoResponse.apps:type_name -> CMsgClientPICSProductInfoResponse.AppInfo
	17, // 6: CMsgClientPICSProductInfoResponse.packages:type_name -> CMsgClientPICSProductInfoResponse.PackageInfo
	18, // 7: CMsgClientPICSAccessTokenResponse.package_access_tokens:type_name -> CMsgClientPICSAccessTokenResponse.PackageToken
	19, // 8: CMsgClientPICSAccessTokenResponse.app_access_tokens:type_name -> CMsgClientPICSAccessTokenResponse.AppToken
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_appinfo_proto_init() }
func file_steammessages_clientserver_appinfo_proto_init() {
	if File_steammessages_clientserver_appinfo_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_appinfo_proto_rawDesc), len(file_steammessages_clientserver_appinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_appinfo_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_appinfo_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_appinfo_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_appinfo_proto = out.File
	file_steammessages_clientserver_appinfo_proto_goTypes = nil
	file_steammessages_clientserver_appinfo_proto_depIdxs = nil
}
