// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_contentsystem.steamclient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CContentServerDirectory_ConnectedSteamPipeServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	SourceId      *int32                 `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Hostname      *string                `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) Reset() {
	*x = CContentServerDirectory_ConnectedSteamPipeServerInfo{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_ConnectedSteamPipeServerInfo) ProtoMessage() {}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_ConnectedSteamPipeServerInfo.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_ConnectedSteamPipeServerInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{0}
}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) GetSourceId() int32 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

func (x *CContentServerDirectory_ConnectedSteamPipeServerInfo) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

type CContentServerDirectory_GetServersForSteamPipe_Request struct {
	state              protoimpl.MessageState                                  `protogen:"open.v1"`
	CellId             *uint32                                                 `protobuf:"varint,1,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	MaxServers         *uint32                                                 `protobuf:"varint,2,opt,name=max_servers,json=maxServers,def=20" json:"max_servers,omitempty"`
	IpOverride         *string                                                 `protobuf:"bytes,3,opt,name=ip_override,json=ipOverride" json:"ip_override,omitempty"`
	LauncherType       *int32                                                  `protobuf:"varint,4,opt,name=launcher_type,json=launcherType,def=0" json:"launcher_type,omitempty"`
	Ipv6Public         *string                                                 `protobuf:"bytes,5,opt,name=ipv6_public,json=ipv6Public" json:"ipv6_public,omitempty"`
	CurrentConnections []*CContentServerDirectory_ConnectedSteamPipeServerInfo `protobuf:"bytes,6,rep,name=current_connections,json=currentConnections" json:"current_connections,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CContentServerDirectory_GetServersForSteamPipe_Request fields.
const (
	Default_CContentServerDirectory_GetServersForSteamPipe_Request_MaxServers   = uint32(20)
	Default_CContentServerDirectory_GetServersForSteamPipe_Request_LauncherType = int32(0)
)

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) Reset() {
	*x = CContentServerDirectory_GetServersForSteamPipe_Request{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_GetServersForSteamPipe_Request) ProtoMessage() {}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_GetServersForSteamPipe_Request.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_GetServersForSteamPipe_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{1}
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetCellId() uint32 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetMaxServers() uint32 {
	if x != nil && x.MaxServers != nil {
		return *x.MaxServers
	}
	return Default_CContentServerDirectory_GetServersForSteamPipe_Request_MaxServers
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetIpOverride() string {
	if x != nil && x.IpOverride != nil {
		return *x.IpOverride
	}
	return ""
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetLauncherType() int32 {
	if x != nil && x.LauncherType != nil {
		return *x.LauncherType
	}
	return Default_CContentServerDirectory_GetServersForSteamPipe_Request_LauncherType
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetIpv6Public() string {
	if x != nil && x.Ipv6Public != nil {
		return *x.Ipv6Public
	}
	return ""
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Request) GetCurrentConnections() []*CContentServerDirectory_ConnectedSteamPipeServerInfo {
	if x != nil {
		return x.CurrentConnections
	}
	return nil
}

type CContentServerDirectory_ServerInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Type                     *string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	SourceId                 *int32                 `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	CellId                   *int32                 `protobuf:"varint,3,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	Load                     *int32                 `protobuf:"varint,4,opt,name=load" json:"load,omitempty"`
	WeightedLoad             *float32               `protobuf:"fixed32,5,opt,name=weighted_load,json=weightedLoad" json:"weighted_load,omitempty"`
	NumEntriesInClientList   *int32                 `protobuf:"varint,6,opt,name=num_entries_in_client_list,json=numEntriesInClientList" json:"num_entries_in_client_list,omitempty"`
	SteamChinaOnly           *bool                  `protobuf:"varint,7,opt,name=steam_china_only,json=steamChinaOnly" json:"steam_china_only,omitempty"`
	Host                     *string                `protobuf:"bytes,8,opt,name=host" json:"host,omitempty"`
	Vhost                    *string                `protobuf:"bytes,9,opt,name=vhost" json:"vhost,omitempty"`
	UseAsProxy               *bool                  `protobuf:"varint,10,opt,name=use_as_proxy,json=useAsProxy" json:"use_as_proxy,omitempty"`
	ProxyRequestPathTemplate *string                `protobuf:"bytes,11,opt,name=proxy_request_path_template,json=proxyRequestPathTemplate" json:"proxy_request_path_template,omitempty"`
	HttpsSupport             *string                `protobuf:"bytes,12,opt,name=https_support,json=httpsSupport" json:"https_support,omitempty"`
	AllowedAppIds            []uint32               `protobuf:"varint,13,rep,name=allowed_app_ids,json=allowedAppIds" json:"allowed_app_ids,omitempty"`
	PriorityClass            *uint32                `protobuf:"varint,15,opt,name=priority_class,json=priorityClass" json:"priority_class,omitempty"`
	BypassProxiesOfType      []string               `protobuf:"bytes,16,rep,name=bypass_proxies_of_type,json=bypassProxiesOfType" json:"bypass_proxies_of_type,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CContentServerDirectory_ServerInfo) Reset() {
	*x = CContentServerDirectory_ServerInfo{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_ServerInfo) ProtoMessage() {}

func (x *CContentServerDirectory_ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_ServerInfo.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_ServerInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{2}
}

func (x *CContentServerDirectory_ServerInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CContentServerDirectory_ServerInfo) GetSourceId() int32 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetCellId() int32 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetLoad() int32 {
	if x != nil && x.Load != nil {
		return *x.Load
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetWeightedLoad() float32 {
	if x != nil && x.WeightedLoad != nil {
		return *x.WeightedLoad
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetNumEntriesInClientList() int32 {
	if x != nil && x.NumEntriesInClientList != nil {
		return *x.NumEntriesInClientList
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetSteamChinaOnly() bool {
	if x != nil && x.SteamChinaOnly != nil {
		return *x.SteamChinaOnly
	}
	return false
}

func (x *CContentServerDirectory_ServerInfo) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *CContentServerDirectory_ServerInfo) GetVhost() string {
	if x != nil && x.Vhost != nil {
		return *x.Vhost
	}
	return ""
}

func (x *CContentServerDirectory_ServerInfo) GetUseAsProxy() bool {
	if x != nil && x.UseAsProxy != nil {
		return *x.UseAsProxy
	}
	return false
}

func (x *CContentServerDirectory_ServerInfo) GetProxyRequestPathTemplate() string {
	if x != nil && x.ProxyRequestPathTemplate != nil {
		return *x.ProxyRequestPathTemplate
	}
	return ""
}

func (x *CContentServerDirectory_ServerInfo) GetHttpsSupport() string {
	if x != nil && x.HttpsSupport != nil {
		return *x.HttpsSupport
	}
	return ""
}

func (x *CContentServerDirectory_ServerInfo) GetAllowedAppIds() []uint32 {
	if x != nil {
		return x.AllowedAppIds
	}
	return nil
}

func (x *CContentServerDirectory_ServerInfo) GetPriorityClass() uint32 {
	if x != nil && x.PriorityClass != nil {
		return *x.PriorityClass
	}
	return 0
}

func (x *CContentServerDirectory_ServerInfo) GetBypassProxiesOfType() []string {
	if x != nil {
		return x.BypassProxiesOfType
	}
	return nil
}

type CContentServerDirectory_GetServersForSteamPipe_Response struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Servers       []*CContentServerDirectory_ServerInfo `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	NoChange      *bool                                 `protobuf:"varint,2,opt,name=no_change,json=noChange" json:"no_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Response) Reset() {
	*x = CContentServerDirectory_GetServersForSteamPipe_Response{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_GetServersForSteamPipe_Response) ProtoMessage() {}

func (x *CContentServerDirectory_GetServersForSteamPipe_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_GetServersForSteamPipe_Response.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_GetServersForSteamPipe_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{3}
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Response) GetServers() []*CContentServerDirectory_ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *CContentServerDirectory_GetServersForSteamPipe_Response) GetNoChange() bool {
	if x != nil && x.NoChange != nil {
		return *x.NoChange
	}
	return false
}

type CContentServerDirectory_GetManifestRequestCode_Request struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	DepotId            *uint32                `protobuf:"varint,2,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	ManifestId         *uint64                `protobuf:"varint,3,opt,name=manifest_id,json=manifestId" json:"manifest_id,omitempty"`
	AppBranch          *string                `protobuf:"bytes,4,opt,name=app_branch,json=appBranch" json:"app_branch,omitempty"`
	BranchPasswordHash *string                `protobuf:"bytes,5,opt,name=branch_password_hash,json=branchPasswordHash" json:"branch_password_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) Reset() {
	*x = CContentServerDirectory_GetManifestRequestCode_Request{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_GetManifestRequestCode_Request) ProtoMessage() {}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_GetManifestRequestCode_Request.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_GetManifestRequestCode_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{4}
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) GetManifestId() uint64 {
	if x != nil && x.ManifestId != nil {
		return *x.ManifestId
	}
	return 0
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) GetAppBranch() string {
	if x != nil && x.AppBranch != nil {
		return *x.AppBranch
	}
	return ""
}

func (x *CContentServerDirectory_GetManifestRequestCode_Request) GetBranchPasswordHash() string {
	if x != nil && x.BranchPasswordHash != nil {
		return *x.BranchPasswordHash
	}
	return ""
}

type CContentServerDirectory_GetManifestRequestCode_Response struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ManifestRequestCode *uint64                `protobuf:"varint,1,opt,name=manifest_request_code,json=manifestRequestCode" json:"manifest_request_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CContentServerDirectory_GetManifestRequestCode_Response) Reset() {
	*x = CContentServerDirectory_GetManifestRequestCode_Response{}
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CContentServerDirectory_GetManifestRequestCode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CContentServerDirectory_GetManifestRequestCode_Response) ProtoMessage() {}

func (x *CContentServerDirectory_GetManifestRequestCode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_contentsystem_steamclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CContentServerDirectory_GetManifestRequestCode_Response.ProtoReflect.Descriptor instead.
func (*CContentServerDirectory_GetManifestRequestCode_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_contentsystem_steamclient_proto_rawDescGZIP(), []int{5}
}

func (x *CContentServerDirectory_GetManifestRequestCode_Response) GetManifestRequestCode() uint64 {
	if x != nil && x.ManifestRequestCode != nil {
		return *x.ManifestRequestCode
	}
	return 0
}

var File_steammessages_contentsystem_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_contentsystem_steamclient_proto_rawDesc = "" +
	"\n" +
	"-steammessages_contentsystem.steamclient.proto\"\x83\x01\n" +
	"4CContentServerDirectory_ConnectedSteamPipeServerInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x05R\bsourceId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"\xc8\x02\n" +
	"6CContentServerDirectory_GetServersForSteamPipe_Request\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\rR\x06cellId\x12#\n" +
	"\vmax_servers\x18\x02 \x01(\r:\x0220R\n" +
	"maxServers\x12\x1f\n" +
	"\vip_override\x18\x03 \x01(\tR\n" +
	"ipOverride\x12&\n" +
	"\rlauncher_type\x18\x04 \x01(\x05:\x010R\flauncherType\x12\x1f\n" +
	"\vipv6_public\x18\x05 \x01(\tR\n" +
	"ipv6Public\x12f\n" +
	"\x13current_connections\x18\x06 \x03(\v25.CContentServerDirectory_ConnectedSteamPipeServerInfoR\x12currentConnections\"\xc1\x04\n" +
	"\"CContentServerDirectory_ServerInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x05R\bsourceId\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\x05R\x06cellId\x12\x12\n" +
	"\x04load\x18\x04 \x01(\x05R\x04load\x12#\n" +
	"\rweighted_load\x18\x05 \x01(\x02R\fweightedLoad\x12:\n" +
	"\x1anum_entries_in_client_list\x18\x06 \x01(\x05R\x16numEntriesInClientList\x12(\n" +
	"\x10steam_china_only\x18\a \x01(\bR\x0esteamChinaOnly\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x12\x14\n" +
	"\x05vhost\x18\t \x01(\tR\x05vhost\x12 \n" +
	"\fuse_as_proxy\x18\n" +
	" \x01(\bR\n" +
	"useAsProxy\x12=\n" +
	"\x1bproxy_request_path_template\x18\v \x01(\tR\x18proxyRequestPathTemplate\x12#\n" +
	"\rhttps_support\x18\f \x01(\tR\fhttpsSupport\x12&\n" +
	"\x0fallowed_app_ids\x18\r \x03(\rR\rallowedAppIds\x12%\n" +
	"\x0epriority_class\x18\x0f \x01(\rR\rpriorityClass\x123\n" +
	"\x16bypass_proxies_of_type\x18\x10 \x03(\tR\x13bypassProxiesOfType\"\x95\x01\n" +
	"7CContentServerDirectory_GetServersForSteamPipe_Response\x12=\n" +
	"\aservers\x18\x01 \x03(\v2#.CContentServerDirectory_ServerInfoR\aservers\x12\x1b\n" +
	"\tno_change\x18\x02 \x01(\bR\bnoChange\"\xdc\x01\n" +
	"6CContentServerDirectory_GetManifestRequestCode_Request\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x19\n" +
	"\bdepot_id\x18\x02 \x01(\rR\adepotId\x12\x1f\n" +
	"\vmanifest_id\x18\x03 \x01(\x04R\n" +
	"manifestId\x12\x1d\n" +
	"\n" +
	"app_branch\x18\x04 \x01(\tR\tappBranch\x120\n" +
	"\x14branch_password_hash\x18\x05 \x01(\tR\x12branchPasswordHash\"m\n" +
	"7CContentServerDirectory_GetManifestRequestCode_Response\x122\n" +
	"\x15manifest_request_code\x18\x01 \x01(\x04R\x13manifestRequestCodeB\x03\x80\x01\x01"

var (
	file_steammessages_contentsystem_steamclient_proto_rawDescOnce sync.Once
	file_steammessages_contentsystem_steamclient_proto_rawDescData []byte
)

func file_steammessages_contentsystem_steamclient_proto_rawDescGZIP() []byte {
	file_steammessages_contentsystem_steamclient_proto_rawDescOnce.Do(func() {
		file_steammessages_contentsystem_steamclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_contentsystem_steamclient_proto_rawDesc), len(file_steammessages_contentsystem_steamclient_proto_rawDesc)))
	})
	return file_steammessages_contentsystem_steamclient_proto_rawDescData
}

var file_steammessages_contentsystem_steamclient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_steammessages_contentsystem_steamclient_proto_goTypes = []any{
	(*CContentServerDirectory_ConnectedSteamPipeServerInfo)(nil),    // 0: CContentServerDirectory_ConnectedSteamPipeServerInfo
	(*CContentServerDirectory_GetServersForSteamPipe_Request)(nil),  // 1: CContentServerDirectory_GetServersForSteamPipe_Request
	(*CContentServerDirectory_ServerInfo)(nil),                      // 2: CContentServerDirectory_ServerInfo
	(*CContentServerDirectory_GetServersForSteamPipe_Response)(nil), // 3: CContentServerDirectory_GetServersForSteamPipe_Response
	(*CContentServerDirectory_GetManifestRequestCode_Request)(nil),  // 4: CContentServerDirectory_GetManifestRequestCode_Request
	(*CContentServerDirectory_GetManifestRequestCode_Response)(nil), // 5: CContentServerDirectory_GetManifestRequestCode_Response
}
var file_steammessages_contentsystem_steamclient_proto_depIdxs = []int32{
	0, // 0: CContentServerDirectory_GetServersForSteamPipe_Request.current_connections:type_name -> CContentServerDirectory_ConnectedSteamPipeServerInfo
	2, // 1: CContentServerDirectory_GetServersForSteamPipe_Response.servers:type_name -> CContentServerDirectory_ServerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_steammessages_contentsystem_steamclient_proto_init() }
func file_steammessages_contentsystem_steamclient_proto_init() {
	if File_steammessages_contentsystem_steamclient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_contentsystem_steamclient_proto_rawDesc), len(file_steammessages_contentsystem_steamclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_contentsystem_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_contentsystem_steamclient_proto_depIdxs,
		MessageInfos:      file_steammessages_contentsystem_steamclient_proto_msgTypes,
	}.Build()
	File_steammessages_contentsystem_steamclient_proto = out.File
	file_steammessages_contentsystem_steamclient_proto_goTypes = nil
	file_steammessages_contentsystem_steamclient_proto_depIdxs = nil
}
