// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_clientserver_appinfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientPICSProductInfoRequest struct {
	state                         protoimpl.MessageState                          `protogen:"open.v1"`
	Packages                      []*CMsgClientPICSProductInfoRequest_PackageInfo `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
	Apps                          []*CMsgClientPICSProductInfoRequest_AppInfo     `protobuf:"bytes,2,rep,name=apps" json:"apps,omitempty"`
	MetaDataOnly                  *bool                                           `protobuf:"varint,3,opt,name=meta_data_only,json=metaDataOnly" json:"meta_data_only,omitempty"`
	NumPrevFailed                 *uint32                                         `protobuf:"varint,4,opt,name=num_prev_failed,json=numPrevFailed" json:"num_prev_failed,omitempty"`
	OBSOLETESupportsPackageTokens *uint32                                         `protobuf:"varint,5,opt,name=OBSOLETE_supports_package_tokens,json=OBSOLETESupportsPackageTokens" json:"OBSOLETE_supports_package_tokens,omitempty"`
	SequenceNumber                *uint32                                         `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	SingleResponse                *bool                                           `protobuf:"varint,7,opt,name=single_response,json=singleResponse" json:"single_response,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest) Reset() {
	*x = CMsgClientPICSProductInfoRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientPICSProductInfoRequest) GetPackages() []*CMsgClientPICSProductInfoRequest_PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CMsgClientPICSProductInfoRequest) GetApps() []*CMsgClientPICSProductInfoRequest_AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CMsgClientPICSProductInfoRequest) GetMetaDataOnly() bool {
	if x != nil && x.MetaDataOnly != nil {
		return *x.MetaDataOnly
	}
	return false
}

func (x *CMsgClientPICSProductInfoRequest) GetNumPrevFailed() uint32 {
	if x != nil && x.NumPrevFailed != nil {
		return *x.NumPrevFailed
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetOBSOLETESupportsPackageTokens() uint32 {
	if x != nil && x.OBSOLETESupportsPackageTokens != nil {
		return *x.OBSOLETESupportsPackageTokens
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetSequenceNumber() uint32 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest) GetSingleResponse() bool {
	if x != nil && x.SingleResponse != nil {
		return *x.SingleResponse
	}
	return false
}

type CMsgClientPICSProductInfoResponse struct {
	state             protoimpl.MessageState                           `protogen:"open.v1"`
	Apps              []*CMsgClientPICSProductInfoResponse_AppInfo     `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	UnknownAppids     []uint32                                         `protobuf:"varint,2,rep,name=unknown_appids,json=unknownAppids" json:"unknown_appids,omitempty"`
	Packages          []*CMsgClientPICSProductInfoResponse_PackageInfo `protobuf:"bytes,3,rep,name=packages" json:"packages,omitempty"`
	UnknownPackageids []uint32                                         `protobuf:"varint,4,rep,name=unknown_packageids,json=unknownPackageids" json:"unknown_packageids,omitempty"`
	MetaDataOnly      *bool                                            `protobuf:"varint,5,opt,name=meta_data_only,json=metaDataOnly" json:"meta_data_only,omitempty"`
	ResponsePending   *bool                                            `protobuf:"varint,6,opt,name=response_pending,json=responsePending" json:"response_pending,omitempty"`
	HttpMinSize       *uint32                                          `protobuf:"varint,7,opt,name=http_min_size,json=httpMinSize" json:"http_min_size,omitempty"`
	HttpHost          *string                                          `protobuf:"bytes,8,opt,name=http_host,json=httpHost" json:"http_host,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse) Reset() {
	*x = CMsgClientPICSProductInfoResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientPICSProductInfoResponse) GetApps() []*CMsgClientPICSProductInfoResponse_AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetUnknownAppids() []uint32 {
	if x != nil {
		return x.UnknownAppids
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetPackages() []*CMsgClientPICSProductInfoResponse_PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetUnknownPackageids() []uint32 {
	if x != nil {
		return x.UnknownPackageids
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse) GetMetaDataOnly() bool {
	if x != nil && x.MetaDataOnly != nil {
		return *x.MetaDataOnly
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse) GetResponsePending() bool {
	if x != nil && x.ResponsePending != nil {
		return *x.ResponsePending
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse) GetHttpMinSize() uint32 {
	if x != nil && x.HttpMinSize != nil {
		return *x.HttpMinSize
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse) GetHttpHost() string {
	if x != nil && x.HttpHost != nil {
		return *x.HttpHost
	}
	return ""
}

type CMsgClientPICSAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageids    []uint32               `protobuf:"varint,1,rep,name=packageids" json:"packageids,omitempty"`
	Appids        []uint32               `protobuf:"varint,2,rep,name=appids" json:"appids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenRequest) Reset() {
	*x = CMsgClientPICSAccessTokenRequest{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenRequest) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientPICSAccessTokenRequest) GetPackageids() []uint32 {
	if x != nil {
		return x.Packageids
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenRequest) GetAppids() []uint32 {
	if x != nil {
		return x.Appids
	}
	return nil
}

type CMsgClientPICSAccessTokenResponse struct {
	state               protoimpl.MessageState                            `protogen:"open.v1"`
	PackageAccessTokens []*CMsgClientPICSAccessTokenResponse_PackageToken `protobuf:"bytes,1,rep,name=package_access_tokens,json=packageAccessTokens" json:"package_access_tokens,omitempty"`
	PackageDeniedTokens []uint32                                          `protobuf:"varint,2,rep,name=package_denied_tokens,json=packageDeniedTokens" json:"package_denied_tokens,omitempty"`
	AppAccessTokens     []*CMsgClientPICSAccessTokenResponse_AppToken     `protobuf:"bytes,3,rep,name=app_access_tokens,json=appAccessTokens" json:"app_access_tokens,omitempty"`
	AppDeniedTokens     []uint32                                          `protobuf:"varint,4,rep,name=app_denied_tokens,json=appDeniedTokens" json:"app_denied_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse) Reset() {
	*x = CMsgClientPICSAccessTokenResponse{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientPICSAccessTokenResponse) GetPackageAccessTokens() []*CMsgClientPICSAccessTokenResponse_PackageToken {
	if x != nil {
		return x.PackageAccessTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetPackageDeniedTokens() []uint32 {
	if x != nil {
		return x.PackageDeniedTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetAppAccessTokens() []*CMsgClientPICSAccessTokenResponse_AppToken {
	if x != nil {
		return x.AppAccessTokens
	}
	return nil
}

func (x *CMsgClientPICSAccessTokenResponse) GetAppDeniedTokens() []uint32 {
	if x != nil {
		return x.AppDeniedTokens
	}
	return nil
}

type CMsgClientPICSProductInfoRequest_AppInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Appid              *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AccessToken        *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	OnlyPublicObsolete *bool                  `protobuf:"varint,3,opt,name=only_public_obsolete,json=onlyPublicObsolete" json:"only_public_obsolete,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) Reset() {
	*x = CMsgClientPICSProductInfoRequest_AppInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest_AppInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest_AppInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest_AppInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_AppInfo) GetOnlyPublicObsolete() bool {
	if x != nil && x.OnlyPublicObsolete != nil {
		return *x.OnlyPublicObsolete
	}
	return false
}

type CMsgClientPICSProductInfoRequest_PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) Reset() {
	*x = CMsgClientPICSProductInfoRequest_PackageInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoRequest_PackageInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoRequest_PackageInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoRequest_PackageInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoRequest_PackageInfo) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

type CMsgClientPICSProductInfoResponse_AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	MissingToken  *bool                  `protobuf:"varint,3,opt,name=missing_token,json=missingToken" json:"missing_token,omitempty"`
	Sha           []byte                 `protobuf:"bytes,4,opt,name=sha" json:"sha,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,5,opt,name=buffer" json:"buffer,omitempty"`
	OnlyPublic    *bool                  `protobuf:"varint,6,opt,name=only_public,json=onlyPublic" json:"only_public,omitempty"`
	Size          *uint32                `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) Reset() {
	*x = CMsgClientPICSProductInfoResponse_AppInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse_AppInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse_AppInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse_AppInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetMissingToken() bool {
	if x != nil && x.MissingToken != nil {
		return *x.MissingToken
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetSha() []byte {
	if x != nil {
		return x.Sha
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetOnlyPublic() bool {
	if x != nil && x.OnlyPublic != nil {
		return *x.OnlyPublic
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_AppInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type CMsgClientPICSProductInfoResponse_PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	ChangeNumber  *uint32                `protobuf:"varint,2,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	MissingToken  *bool                  `protobuf:"varint,3,opt,name=missing_token,json=missingToken" json:"missing_token,omitempty"`
	Sha           []byte                 `protobuf:"bytes,4,opt,name=sha" json:"sha,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,5,opt,name=buffer" json:"buffer,omitempty"`
	Size          *uint32                `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) Reset() {
	*x = CMsgClientPICSProductInfoResponse_PackageInfo{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSProductInfoResponse_PackageInfo) ProtoMessage() {}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSProductInfoResponse_PackageInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSProductInfoResponse_PackageInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetChangeNumber() uint32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetMissingToken() bool {
	if x != nil && x.MissingToken != nil {
		return *x.MissingToken
	}
	return false
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetSha() []byte {
	if x != nil {
		return x.Sha
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *CMsgClientPICSProductInfoResponse_PackageInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type CMsgClientPICSAccessTokenResponse_PackageToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     *uint32                `protobuf:"varint,1,opt,name=packageid" json:"packageid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) Reset() {
	*x = CMsgClientPICSAccessTokenResponse_PackageToken{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse_PackageToken) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse_PackageToken.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse_PackageToken) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) GetPackageid() uint32 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *CMsgClientPICSAccessTokenResponse_PackageToken) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

type CMsgClientPICSAccessTokenResponse_AppToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AccessToken   *uint64                `protobuf:"varint,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) Reset() {
	*x = CMsgClientPICSAccessTokenResponse_AppToken{}
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientPICSAccessTokenResponse_AppToken) ProtoMessage() {}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_appinfo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientPICSAccessTokenResponse_AppToken.ProtoReflect.Descriptor instead.
func (*CMsgClientPICSAccessTokenResponse_AppToken) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_appinfo_proto_rawDescGZIP(), []int{3, 1}
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgClientPICSAccessTokenResponse_AppToken) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

var File_steammessages_clientserver_appinfo_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_appinfo_proto_rawDesc = "" +
	"\n" +
	"(steammessages_clientserver_appinfo.proto\x1a\x18steammessages_base.proto\"\xdb\x04\n" +
	" CMsgClientPICSProductInfoRequest\x12I\n" +
	"\bpackages\x18\x01 \x03(\v2-.CMsgClientPICSProductInfoRequest.PackageInfoR\bpackages\x12=\n" +
	"\x04apps\x18\x02 \x03(\v2).CMsgClientPICSProductInfoRequest.AppInfoR\x04apps\x12$\n" +
	"\x0emeta_data_only\x18\x03 \x01(\bR\fmetaDataOnly\x12&\n" +
	"\x0fnum_prev_failed\x18\x04 \x01(\rR\rnumPrevFailed\x12G\n" +
	" OBSOLETE_supports_package_tokens\x18\x05 \x01(\rR\x1dOBSOLETESupportsPackageTokens\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\rR\x0esequenceNumber\x12'\n" +
	"\x0fsingle_response\x18\a \x01(\bR\x0esingleResponse\x1at\n" +
	"\aAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\x120\n" +
	"\x14only_public_obsolete\x18\x03 \x01(\bR\x12onlyPublicObsolete\x1aN\n" +
	"\vPackageInfo\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\"\x9e\x06\n" +
	"!CMsgClientPICSProductInfoResponse\x12>\n" +
	"\x04apps\x18\x01 \x03(\v2*.CMsgClientPICSProductInfoResponse.AppInfoR\x04apps\x12%\n" +
	"\x0eunknown_appids\x18\x02 \x03(\rR\runknownAppids\x12J\n" +
	"\bpackages\x18\x03 \x03(\v2..CMsgClientPICSProductInfoResponse.PackageInfoR\bpackages\x12-\n" +
	"\x12unknown_packageids\x18\x04 \x03(\rR\x11unknownPackageids\x12$\n" +
	"\x0emeta_data_only\x18\x05 \x01(\bR\fmetaDataOnly\x12)\n" +
	"\x10response_pending\x18\x06 \x01(\bR\x0fresponsePending\x12\"\n" +
	"\rhttp_min_size\x18\a \x01(\rR\vhttpMinSize\x12\x1b\n" +
	"\thttp_host\x18\b \x01(\tR\bhttpHost\x1a\xc8\x01\n" +
	"\aAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12#\n" +
	"\rmissing_token\x18\x03 \x01(\bR\fmissingToken\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\fR\x03sha\x12\x16\n" +
	"\x06buffer\x18\x05 \x01(\fR\x06buffer\x12\x1f\n" +
	"\vonly_public\x18\x06 \x01(\bR\n" +
	"onlyPublic\x12\x12\n" +
	"\x04size\x18\a \x01(\rR\x04size\x1a\xb3\x01\n" +
	"\vPackageInfo\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12#\n" +
	"\rchange_number\x18\x02 \x01(\rR\fchangeNumber\x12#\n" +
	"\rmissing_token\x18\x03 \x01(\bR\fmissingToken\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\fR\x03sha\x12\x16\n" +
	"\x06buffer\x18\x05 \x01(\fR\x06buffer\x12\x12\n" +
	"\x04size\x18\x06 \x01(\rR\x04size:\x04\x88\xb5\x18\x00\"Z\n" +
	" CMsgClientPICSAccessTokenRequest\x12\x1e\n" +
	"\n" +
	"packageids\x18\x01 \x03(\rR\n" +
	"packageids\x12\x16\n" +
	"\x06appids\x18\x02 \x03(\rR\x06appids\"\xd7\x03\n" +
	"!CMsgClientPICSAccessTokenResponse\x12c\n" +
	"\x15package_access_tokens\x18\x01 \x03(\v2/.CMsgClientPICSAccessTokenResponse.PackageTokenR\x13packageAccessTokens\x122\n" +
	"\x15package_denied_tokens\x18\x02 \x03(\rR\x13packageDeniedTokens\x12W\n" +
	"\x11app_access_tokens\x18\x03 \x03(\v2+.CMsgClientPICSAccessTokenResponse.AppTokenR\x0fappAccessTokens\x12*\n" +
	"\x11app_denied_tokens\x18\x04 \x03(\rR\x0fappDeniedTokens\x1aO\n" +
	"\fPackageToken\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessToken\x1aC\n" +
	"\bAppToken\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\x04R\vaccessTokenB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_appinfo_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_appinfo_proto_rawDescData []byte
)

func file_steammessages_clientserver_appinfo_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_appinfo_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_appinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_appinfo_proto_rawDesc), len(file_steammessages_clientserver_appinfo_proto_rawDesc)))
	})
	return file_steammessages_clientserver_appinfo_proto_rawDescData
}

var file_steammessages_clientserver_appinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_steammessages_clientserver_appinfo_proto_goTypes = []any{
	(*CMsgClientPICSProductInfoRequest)(nil),               // 0: CMsgClientPICSProductInfoRequest
	(*CMsgClientPICSProductInfoResponse)(nil),              // 1: CMsgClientPICSProductInfoResponse
	(*CMsgClientPICSAccessTokenRequest)(nil),               // 2: CMsgClientPICSAccessTokenRequest
	(*CMsgClientPICSAccessTokenResponse)(nil),              // 3: CMsgClientPICSAccessTokenResponse
	(*CMsgClientPICSProductInfoRequest_AppInfo)(nil),       // 4: CMsgClientPICSProductInfoRequest.AppInfo
	(*CMsgClientPICSProductInfoRequest_PackageInfo)(nil),   // 5: CMsgClientPICSProductInfoRequest.PackageInfo
	(*CMsgClientPICSProductInfoResponse_AppInfo)(nil),      // 6: CMsgClientPICSProductInfoResponse.AppInfo
	(*CMsgClientPICSProductInfoResponse_PackageInfo)(nil),  // 7: CMsgClientPICSProductInfoResponse.PackageInfo
	(*CMsgClientPICSAccessTokenResponse_PackageToken)(nil), // 8: CMsgClientPICSAccessTokenResponse.PackageToken
	(*CMsgClientPICSAccessTokenResponse_AppToken)(nil),     // 9: CMsgClientPICSAccessTokenResponse.AppToken
}
var file_steammessages_clientserver_appinfo_proto_depIdxs = []int32{
	5, // 0: CMsgClientPICSProductInfoRequest.packages:type_name -> CMsgClientPICSProductInfoRequest.PackageInfo
	4, // 1: CMsgClientPICSProductInfoRequest.apps:type_name -> CMsgClientPICSProductInfoRequest.AppInfo
	6, // 2: CMsgClientPICSProductInfoResponse.apps:type_name -> CMsgClientPICSProductInfoResponse.AppInfo
	7, // 3: CMsgClientPICSProductInfoResponse.packages:type_name -> CMsgClientPICSProductInfoResponse.PackageInfo
	8, // 4: CMsgClientPICSAccessTokenResponse.package_access_tokens:type_name -> CMsgClientPICSAccessTokenResponse.PackageToken
	9, // 5: CMsgClientPICSAccessTokenResponse.app_access_tokens:type_name -> CMsgClientPICSAccessTokenResponse.AppToken
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_appinfo_proto_init() }
func file_steammessages_clientserver_appinfo_proto_init() {
	if File_steammessages_clientserver_appinfo_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_appinfo_proto_rawDesc), len(file_steammessages_clientserver_appinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_appinfo_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_appinfo_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_appinfo_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_appinfo_proto = out.File
	file_steammessages_clientserver_appinfo_proto_goTypes = nil
	file_steammessages_clientserver_appinfo_proto_depIdxs = nil
}
