// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: steammessages_auth.steamclient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAuthTokenPlatformType int32

const (
	EAuthTokenPlatformType_k_EAuthTokenPlatformType_Unknown     EAuthTokenPlatformType = 0
	EAuthTokenPlatformType_k_EAuthTokenPlatformType_SteamClient EAuthTokenPlatformType = 1
	EAuthTokenPlatformType_k_EAuthTokenPlatformType_WebBrowser  EAuthTokenPlatformType = 2
	EAuthTokenPlatformType_k_EAuthTokenPlatformType_MobileApp   EAuthTokenPlatformType = 3
)

// Enum value maps for EAuthTokenPlatformType.
var (
	EAuthTokenPlatformType_name = map[int32]string{
		0: "k_EAuthTokenPlatformType_Unknown",
		1: "k_EAuthTokenPlatformType_SteamClient",
		2: "k_EAuthTokenPlatformType_WebBrowser",
		3: "k_EAuthTokenPlatformType_MobileApp",
	}
	EAuthTokenPlatformType_value = map[string]int32{
		"k_EAuthTokenPlatformType_Unknown":     0,
		"k_EAuthTokenPlatformType_SteamClient": 1,
		"k_EAuthTokenPlatformType_WebBrowser":  2,
		"k_EAuthTokenPlatformType_MobileApp":   3,
	}
)

func (x EAuthTokenPlatformType) Enum() *EAuthTokenPlatformType {
	p := new(EAuthTokenPlatformType)
	*p = x
	return p
}

func (x EAuthTokenPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAuthTokenPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_auth_steamclient_proto_enumTypes[0].Descriptor()
}

func (EAuthTokenPlatformType) Type() protoreflect.EnumType {
	return &file_steammessages_auth_steamclient_proto_enumTypes[0]
}

func (x EAuthTokenPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAuthTokenPlatformType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAuthTokenPlatformType(num)
	return nil
}

// Deprecated: Use EAuthTokenPlatformType.Descriptor instead.
func (EAuthTokenPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{0}
}

type EAuthSessionGuardType int32

const (
	EAuthSessionGuardType_k_EAuthSessionGuardType_Unknown            EAuthSessionGuardType = 0
	EAuthSessionGuardType_k_EAuthSessionGuardType_None               EAuthSessionGuardType = 1
	EAuthSessionGuardType_k_EAuthSessionGuardType_EmailCode          EAuthSessionGuardType = 2
	EAuthSessionGuardType_k_EAuthSessionGuardType_DeviceCode         EAuthSessionGuardType = 3
	EAuthSessionGuardType_k_EAuthSessionGuardType_DeviceConfirmation EAuthSessionGuardType = 4
	EAuthSessionGuardType_k_EAuthSessionGuardType_EmailConfirmation  EAuthSessionGuardType = 5
	EAuthSessionGuardType_k_EAuthSessionGuardType_MachineToken       EAuthSessionGuardType = 6
	EAuthSessionGuardType_k_EAuthSessionGuardType_LegacyMachineAuth  EAuthSessionGuardType = 7
)

// Enum value maps for EAuthSessionGuardType.
var (
	EAuthSessionGuardType_name = map[int32]string{
		0: "k_EAuthSessionGuardType_Unknown",
		1: "k_EAuthSessionGuardType_None",
		2: "k_EAuthSessionGuardType_EmailCode",
		3: "k_EAuthSessionGuardType_DeviceCode",
		4: "k_EAuthSessionGuardType_DeviceConfirmation",
		5: "k_EAuthSessionGuardType_EmailConfirmation",
		6: "k_EAuthSessionGuardType_MachineToken",
		7: "k_EAuthSessionGuardType_LegacyMachineAuth",
	}
	EAuthSessionGuardType_value = map[string]int32{
		"k_EAuthSessionGuardType_Unknown":            0,
		"k_EAuthSessionGuardType_None":               1,
		"k_EAuthSessionGuardType_EmailCode":          2,
		"k_EAuthSessionGuardType_DeviceCode":         3,
		"k_EAuthSessionGuardType_DeviceConfirmation": 4,
		"k_EAuthSessionGuardType_EmailConfirmation":  5,
		"k_EAuthSessionGuardType_MachineToken":       6,
		"k_EAuthSessionGuardType_LegacyMachineAuth":  7,
	}
)

func (x EAuthSessionGuardType) Enum() *EAuthSessionGuardType {
	p := new(EAuthSessionGuardType)
	*p = x
	return p
}

func (x EAuthSessionGuardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAuthSessionGuardType) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_auth_steamclient_proto_enumTypes[1].Descriptor()
}

func (EAuthSessionGuardType) Type() protoreflect.EnumType {
	return &file_steammessages_auth_steamclient_proto_enumTypes[1]
}

func (x EAuthSessionGuardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAuthSessionGuardType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAuthSessionGuardType(num)
	return nil
}

// Deprecated: Use EAuthSessionGuardType.Descriptor instead.
func (EAuthSessionGuardType) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{1}
}

type CAuthentication_GetPasswordRSAPublicKey_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   *string                `protobuf:"bytes,1,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Request) Reset() {
	*x = CAuthentication_GetPasswordRSAPublicKey_Request{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_GetPasswordRSAPublicKey_Request) ProtoMessage() {}

func (x *CAuthentication_GetPasswordRSAPublicKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_GetPasswordRSAPublicKey_Request.ProtoReflect.Descriptor instead.
func (*CAuthentication_GetPasswordRSAPublicKey_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{0}
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Request) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

type CAuthentication_GetPasswordRSAPublicKey_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublickeyMod  *string                `protobuf:"bytes,1,opt,name=publickey_mod,json=publickeyMod" json:"publickey_mod,omitempty"`
	PublickeyExp  *string                `protobuf:"bytes,2,opt,name=publickey_exp,json=publickeyExp" json:"publickey_exp,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) Reset() {
	*x = CAuthentication_GetPasswordRSAPublicKey_Response{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_GetPasswordRSAPublicKey_Response) ProtoMessage() {}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_GetPasswordRSAPublicKey_Response.ProtoReflect.Descriptor instead.
func (*CAuthentication_GetPasswordRSAPublicKey_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{1}
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) GetPublickeyMod() string {
	if x != nil && x.PublickeyMod != nil {
		return *x.PublickeyMod
	}
	return ""
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) GetPublickeyExp() string {
	if x != nil && x.PublickeyExp != nil {
		return *x.PublickeyExp
	}
	return ""
}

func (x *CAuthentication_GetPasswordRSAPublicKey_Response) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type CAuthentication_DeviceDetails struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	DeviceFriendlyName *string                 `protobuf:"bytes,1,opt,name=device_friendly_name,json=deviceFriendlyName" json:"device_friendly_name,omitempty"`
	PlatformType       *EAuthTokenPlatformType `protobuf:"varint,2,opt,name=platform_type,json=platformType,enum=EAuthTokenPlatformType,def=0" json:"platform_type,omitempty"`
	OsType             *int32                  `protobuf:"varint,3,opt,name=os_type,json=osType" json:"os_type,omitempty"`
	GamingDeviceType   *uint32                 `protobuf:"varint,4,opt,name=gaming_device_type,json=gamingDeviceType" json:"gaming_device_type,omitempty"`
	ClientCount        *uint32                 `protobuf:"varint,5,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
	MachineId          []byte                  `protobuf:"bytes,6,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CAuthentication_DeviceDetails fields.
const (
	Default_CAuthentication_DeviceDetails_PlatformType = EAuthTokenPlatformType_k_EAuthTokenPlatformType_Unknown
)

func (x *CAuthentication_DeviceDetails) Reset() {
	*x = CAuthentication_DeviceDetails{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_DeviceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_DeviceDetails) ProtoMessage() {}

func (x *CAuthentication_DeviceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_DeviceDetails.ProtoReflect.Descriptor instead.
func (*CAuthentication_DeviceDetails) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{2}
}

func (x *CAuthentication_DeviceDetails) GetDeviceFriendlyName() string {
	if x != nil && x.DeviceFriendlyName != nil {
		return *x.DeviceFriendlyName
	}
	return ""
}

func (x *CAuthentication_DeviceDetails) GetPlatformType() EAuthTokenPlatformType {
	if x != nil && x.PlatformType != nil {
		return *x.PlatformType
	}
	return Default_CAuthentication_DeviceDetails_PlatformType
}

func (x *CAuthentication_DeviceDetails) GetOsType() int32 {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return 0
}

func (x *CAuthentication_DeviceDetails) GetGamingDeviceType() uint32 {
	if x != nil && x.GamingDeviceType != nil {
		return *x.GamingDeviceType
	}
	return 0
}

func (x *CAuthentication_DeviceDetails) GetClientCount() uint32 {
	if x != nil && x.ClientCount != nil {
		return *x.ClientCount
	}
	return 0
}

func (x *CAuthentication_DeviceDetails) GetMachineId() []byte {
	if x != nil {
		return x.MachineId
	}
	return nil
}

type CAuthentication_AllowedConfirmation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationType  *EAuthSessionGuardType `protobuf:"varint,1,opt,name=confirmation_type,json=confirmationType,enum=EAuthSessionGuardType,def=0" json:"confirmation_type,omitempty"`
	AssociatedMessage *string                `protobuf:"bytes,2,opt,name=associated_message,json=associatedMessage" json:"associated_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for CAuthentication_AllowedConfirmation fields.
const (
	Default_CAuthentication_AllowedConfirmation_ConfirmationType = EAuthSessionGuardType_k_EAuthSessionGuardType_Unknown
)

func (x *CAuthentication_AllowedConfirmation) Reset() {
	*x = CAuthentication_AllowedConfirmation{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_AllowedConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_AllowedConfirmation) ProtoMessage() {}

func (x *CAuthentication_AllowedConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_AllowedConfirmation.ProtoReflect.Descriptor instead.
func (*CAuthentication_AllowedConfirmation) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{3}
}

func (x *CAuthentication_AllowedConfirmation) GetConfirmationType() EAuthSessionGuardType {
	if x != nil && x.ConfirmationType != nil {
		return *x.ConfirmationType
	}
	return Default_CAuthentication_AllowedConfirmation_ConfirmationType
}

func (x *CAuthentication_AllowedConfirmation) GetAssociatedMessage() string {
	if x != nil && x.AssociatedMessage != nil {
		return *x.AssociatedMessage
	}
	return ""
}

type CAuthentication_BeginAuthSessionViaCredentials_Request struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	DeviceFriendlyName  *string                        `protobuf:"bytes,1,opt,name=device_friendly_name,json=deviceFriendlyName" json:"device_friendly_name,omitempty"`
	AccountName         *string                        `protobuf:"bytes,2,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	EncryptedPassword   *string                        `protobuf:"bytes,3,opt,name=encrypted_password,json=encryptedPassword" json:"encrypted_password,omitempty"`
	EncryptionTimestamp *uint64                        `protobuf:"varint,4,opt,name=encryption_timestamp,json=encryptionTimestamp" json:"encryption_timestamp,omitempty"`
	RememberLogin       *bool                          `protobuf:"varint,5,opt,name=remember_login,json=rememberLogin" json:"remember_login,omitempty"`
	PlatformType        *EAuthTokenPlatformType        `protobuf:"varint,6,opt,name=platform_type,json=platformType,enum=EAuthTokenPlatformType,def=0" json:"platform_type,omitempty"`
	Persistence         *ESessionPersistence           `protobuf:"varint,7,opt,name=persistence,enum=ESessionPersistence,def=1" json:"persistence,omitempty"`
	WebsiteId           *string                        `protobuf:"bytes,8,opt,name=website_id,json=websiteId,def=Unknown" json:"website_id,omitempty"`
	DeviceDetails       *CAuthentication_DeviceDetails `protobuf:"bytes,9,opt,name=device_details,json=deviceDetails" json:"device_details,omitempty"`
	GuardData           *string                        `protobuf:"bytes,10,opt,name=guard_data,json=guardData" json:"guard_data,omitempty"`
	Language            *uint32                        `protobuf:"varint,11,opt,name=language" json:"language,omitempty"`
	QosLevel            *int32                         `protobuf:"varint,12,opt,name=qos_level,json=qosLevel,def=2" json:"qos_level,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for CAuthentication_BeginAuthSessionViaCredentials_Request fields.
const (
	Default_CAuthentication_BeginAuthSessionViaCredentials_Request_PlatformType = EAuthTokenPlatformType_k_EAuthTokenPlatformType_Unknown
	Default_CAuthentication_BeginAuthSessionViaCredentials_Request_Persistence  = ESessionPersistence_k_ESessionPersistence_Persistent
	Default_CAuthentication_BeginAuthSessionViaCredentials_Request_WebsiteId    = string("Unknown")
	Default_CAuthentication_BeginAuthSessionViaCredentials_Request_QosLevel     = int32(2)
)

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) Reset() {
	*x = CAuthentication_BeginAuthSessionViaCredentials_Request{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_BeginAuthSessionViaCredentials_Request) ProtoMessage() {}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_BeginAuthSessionViaCredentials_Request.ProtoReflect.Descriptor instead.
func (*CAuthentication_BeginAuthSessionViaCredentials_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{4}
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetDeviceFriendlyName() string {
	if x != nil && x.DeviceFriendlyName != nil {
		return *x.DeviceFriendlyName
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetEncryptedPassword() string {
	if x != nil && x.EncryptedPassword != nil {
		return *x.EncryptedPassword
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetEncryptionTimestamp() uint64 {
	if x != nil && x.EncryptionTimestamp != nil {
		return *x.EncryptionTimestamp
	}
	return 0
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetRememberLogin() bool {
	if x != nil && x.RememberLogin != nil {
		return *x.RememberLogin
	}
	return false
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetPlatformType() EAuthTokenPlatformType {
	if x != nil && x.PlatformType != nil {
		return *x.PlatformType
	}
	return Default_CAuthentication_BeginAuthSessionViaCredentials_Request_PlatformType
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetPersistence() ESessionPersistence {
	if x != nil && x.Persistence != nil {
		return *x.Persistence
	}
	return Default_CAuthentication_BeginAuthSessionViaCredentials_Request_Persistence
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetWebsiteId() string {
	if x != nil && x.WebsiteId != nil {
		return *x.WebsiteId
	}
	return Default_CAuthentication_BeginAuthSessionViaCredentials_Request_WebsiteId
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetDeviceDetails() *CAuthentication_DeviceDetails {
	if x != nil {
		return x.DeviceDetails
	}
	return nil
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetGuardData() string {
	if x != nil && x.GuardData != nil {
		return *x.GuardData
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetLanguage() uint32 {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return 0
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Request) GetQosLevel() int32 {
	if x != nil && x.QosLevel != nil {
		return *x.QosLevel
	}
	return Default_CAuthentication_BeginAuthSessionViaCredentials_Request_QosLevel
}

type CAuthentication_BeginAuthSessionViaCredentials_Response struct {
	state                protoimpl.MessageState                 `protogen:"open.v1"`
	ClientId             *uint64                                `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	RequestId            []byte                                 `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Interval             *float32                               `protobuf:"fixed32,3,opt,name=interval" json:"interval,omitempty"`
	AllowedConfirmations []*CAuthentication_AllowedConfirmation `protobuf:"bytes,4,rep,name=allowed_confirmations,json=allowedConfirmations" json:"allowed_confirmations,omitempty"`
	Steamid              *uint64                                `protobuf:"varint,5,opt,name=steamid" json:"steamid,omitempty"`
	WeakToken            *string                                `protobuf:"bytes,6,opt,name=weak_token,json=weakToken" json:"weak_token,omitempty"`
	AgreementSessionUrl  *string                                `protobuf:"bytes,7,opt,name=agreement_session_url,json=agreementSessionUrl" json:"agreement_session_url,omitempty"`
	ExtendedErrorMessage *string                                `protobuf:"bytes,8,opt,name=extended_error_message,json=extendedErrorMessage" json:"extended_error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) Reset() {
	*x = CAuthentication_BeginAuthSessionViaCredentials_Response{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_BeginAuthSessionViaCredentials_Response) ProtoMessage() {}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_BeginAuthSessionViaCredentials_Response.ProtoReflect.Descriptor instead.
func (*CAuthentication_BeginAuthSessionViaCredentials_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{5}
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetInterval() float32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetAllowedConfirmations() []*CAuthentication_AllowedConfirmation {
	if x != nil {
		return x.AllowedConfirmations
	}
	return nil
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetWeakToken() string {
	if x != nil && x.WeakToken != nil {
		return *x.WeakToken
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetAgreementSessionUrl() string {
	if x != nil && x.AgreementSessionUrl != nil {
		return *x.AgreementSessionUrl
	}
	return ""
}

func (x *CAuthentication_BeginAuthSessionViaCredentials_Response) GetExtendedErrorMessage() string {
	if x != nil && x.ExtendedErrorMessage != nil {
		return *x.ExtendedErrorMessage
	}
	return ""
}

type CAuthentication_PollAuthSessionStatus_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *uint64                `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	TokenToRevoke *uint64                `protobuf:"fixed64,3,opt,name=token_to_revoke,json=tokenToRevoke" json:"token_to_revoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAuthentication_PollAuthSessionStatus_Request) Reset() {
	*x = CAuthentication_PollAuthSessionStatus_Request{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_PollAuthSessionStatus_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_PollAuthSessionStatus_Request) ProtoMessage() {}

func (x *CAuthentication_PollAuthSessionStatus_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_PollAuthSessionStatus_Request.ProtoReflect.Descriptor instead.
func (*CAuthentication_PollAuthSessionStatus_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{6}
}

func (x *CAuthentication_PollAuthSessionStatus_Request) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *CAuthentication_PollAuthSessionStatus_Request) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *CAuthentication_PollAuthSessionStatus_Request) GetTokenToRevoke() uint64 {
	if x != nil && x.TokenToRevoke != nil {
		return *x.TokenToRevoke
	}
	return 0
}

type CAuthentication_PollAuthSessionStatus_Response struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NewClientId          *uint64                `protobuf:"varint,1,opt,name=new_client_id,json=newClientId" json:"new_client_id,omitempty"`
	NewChallengeUrl      *string                `protobuf:"bytes,2,opt,name=new_challenge_url,json=newChallengeUrl" json:"new_challenge_url,omitempty"`
	RefreshToken         *string                `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	AccessToken          *string                `protobuf:"bytes,4,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	HadRemoteInteraction *bool                  `protobuf:"varint,5,opt,name=had_remote_interaction,json=hadRemoteInteraction" json:"had_remote_interaction,omitempty"`
	AccountName          *string                `protobuf:"bytes,6,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	NewGuardData         *string                `protobuf:"bytes,7,opt,name=new_guard_data,json=newGuardData" json:"new_guard_data,omitempty"`
	AgreementSessionUrl  *string                `protobuf:"bytes,8,opt,name=agreement_session_url,json=agreementSessionUrl" json:"agreement_session_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CAuthentication_PollAuthSessionStatus_Response) Reset() {
	*x = CAuthentication_PollAuthSessionStatus_Response{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_PollAuthSessionStatus_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_PollAuthSessionStatus_Response) ProtoMessage() {}

func (x *CAuthentication_PollAuthSessionStatus_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_PollAuthSessionStatus_Response.ProtoReflect.Descriptor instead.
func (*CAuthentication_PollAuthSessionStatus_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{7}
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetNewClientId() uint64 {
	if x != nil && x.NewClientId != nil {
		return *x.NewClientId
	}
	return 0
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetNewChallengeUrl() string {
	if x != nil && x.NewChallengeUrl != nil {
		return *x.NewChallengeUrl
	}
	return ""
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetHadRemoteInteraction() bool {
	if x != nil && x.HadRemoteInteraction != nil {
		return *x.HadRemoteInteraction
	}
	return false
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetNewGuardData() string {
	if x != nil && x.NewGuardData != nil {
		return *x.NewGuardData
	}
	return ""
}

func (x *CAuthentication_PollAuthSessionStatus_Response) GetAgreementSessionUrl() string {
	if x != nil && x.AgreementSessionUrl != nil {
		return *x.AgreementSessionUrl
	}
	return ""
}

type CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *uint64                `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Steamid       *uint64                `protobuf:"fixed64,2,opt,name=steamid" json:"steamid,omitempty"`
	Code          *string                `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	CodeType      *EAuthSessionGuardType `protobuf:"varint,4,opt,name=code_type,json=codeType,enum=EAuthSessionGuardType,def=0" json:"code_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request fields.
const (
	Default_CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request_CodeType = EAuthSessionGuardType_k_EAuthSessionGuardType_Unknown
)

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) Reset() {
	*x = CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) ProtoMessage() {}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request.ProtoReflect.Descriptor instead.
func (*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{8}
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request) GetCodeType() EAuthSessionGuardType {
	if x != nil && x.CodeType != nil {
		return *x.CodeType
	}
	return Default_CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request_CodeType
}

type CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgreementSessionUrl *string                `protobuf:"bytes,7,opt,name=agreement_session_url,json=agreementSessionUrl" json:"agreement_session_url,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) Reset() {
	*x = CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response{}
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) ProtoMessage() {}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_auth_steamclient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response.ProtoReflect.Descriptor instead.
func (*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_auth_steamclient_proto_rawDescGZIP(), []int{9}
}

func (x *CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response) GetAgreementSessionUrl() string {
	if x != nil && x.AgreementSessionUrl != nil {
		return *x.AgreementSessionUrl
	}
	return ""
}

var File_steammessages_auth_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_auth_steamclient_proto_rawDesc = "" +
	"\n" +
	"$steammessages_auth.steamclient.proto\x1a\venums.proto\"T\n" +
	"/CAuthentication_GetPasswordRSAPublicKey_Request\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"\x9a\x01\n" +
	"0CAuthentication_GetPasswordRSAPublicKey_Response\x12#\n" +
	"\rpublickey_mod\x18\x01 \x01(\tR\fpublickeyMod\x12#\n" +
	"\rpublickey_exp\x18\x02 \x01(\tR\fpublickeyExp\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\xba\x02\n" +
	"\x1dCAuthentication_DeviceDetails\x120\n" +
	"\x14device_friendly_name\x18\x01 \x01(\tR\x12deviceFriendlyName\x12^\n" +
	"\rplatform_type\x18\x02 \x01(\x0e2\x17.EAuthTokenPlatformType: k_EAuthTokenPlatformType_UnknownR\fplatformType\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\x05R\x06osType\x12,\n" +
	"\x12gaming_device_type\x18\x04 \x01(\rR\x10gamingDeviceType\x12!\n" +
	"\fclient_count\x18\x05 \x01(\rR\vclientCount\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x06 \x01(\fR\tmachineId\"\xba\x01\n" +
	"#CAuthentication_AllowedConfirmation\x12d\n" +
	"\x11confirmation_type\x18\x01 \x01(\x0e2\x16.EAuthSessionGuardType:\x1fk_EAuthSessionGuardType_UnknownR\x10confirmationType\x12-\n" +
	"\x12associated_message\x18\x02 \x01(\tR\x11associatedMessage\"\x9a\x05\n" +
	"6CAuthentication_BeginAuthSessionViaCredentials_Request\x120\n" +
	"\x14device_friendly_name\x18\x01 \x01(\tR\x12deviceFriendlyName\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12-\n" +
	"\x12encrypted_password\x18\x03 \x01(\tR\x11encryptedPassword\x121\n" +
	"\x14encryption_timestamp\x18\x04 \x01(\x04R\x13encryptionTimestamp\x12%\n" +
	"\x0eremember_login\x18\x05 \x01(\bR\rrememberLogin\x12^\n" +
	"\rplatform_type\x18\x06 \x01(\x0e2\x17.EAuthTokenPlatformType: k_EAuthTokenPlatformType_UnknownR\fplatformType\x12X\n" +
	"\vpersistence\x18\a \x01(\x0e2\x14.ESessionPersistence: k_ESessionPersistence_PersistentR\vpersistence\x12&\n" +
	"\n" +
	"website_id\x18\b \x01(\t:\aUnknownR\twebsiteId\x12E\n" +
	"\x0edevice_details\x18\t \x01(\v2\x1e.CAuthentication_DeviceDetailsR\rdeviceDetails\x12\x1d\n" +
	"\n" +
	"guard_data\x18\n" +
	" \x01(\tR\tguardData\x12\x1a\n" +
	"\blanguage\x18\v \x01(\rR\blanguage\x12\x1e\n" +
	"\tqos_level\x18\f \x01(\x05:\x012R\bqosLevel\"\x8f\x03\n" +
	"7CAuthentication_BeginAuthSessionViaCredentials_Response\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\fR\trequestId\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\x02R\binterval\x12Y\n" +
	"\x15allowed_confirmations\x18\x04 \x03(\v2$.CAuthentication_AllowedConfirmationR\x14allowedConfirmations\x12\x18\n" +
	"\asteamid\x18\x05 \x01(\x04R\asteamid\x12\x1d\n" +
	"\n" +
	"weak_token\x18\x06 \x01(\tR\tweakToken\x122\n" +
	"\x15agreement_session_url\x18\a \x01(\tR\x13agreementSessionUrl\x124\n" +
	"\x16extended_error_message\x18\b \x01(\tR\x14extendedErrorMessage\"\x93\x01\n" +
	"-CAuthentication_PollAuthSessionStatus_Request\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\fR\trequestId\x12&\n" +
	"\x0ftoken_to_revoke\x18\x03 \x01(\x06R\rtokenToRevoke\"\xfb\x02\n" +
	".CAuthentication_PollAuthSessionStatus_Response\x12\"\n" +
	"\rnew_client_id\x18\x01 \x01(\x04R\vnewClientId\x12*\n" +
	"\x11new_challenge_url\x18\x02 \x01(\tR\x0fnewChallengeUrl\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x124\n" +
	"\x16had_remote_interaction\x18\x05 \x01(\bR\x14hadRemoteInteraction\x12!\n" +
	"\faccount_name\x18\x06 \x01(\tR\vaccountName\x12$\n" +
	"\x0enew_guard_data\x18\a \x01(\tR\fnewGuardData\x122\n" +
	"\x15agreement_session_url\x18\b \x01(\tR\x13agreementSessionUrl\"\xde\x01\n" +
	";CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x18\n" +
	"\asteamid\x18\x02 \x01(\x06R\asteamid\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12T\n" +
	"\tcode_type\x18\x04 \x01(\x0e2\x16.EAuthSessionGuardType:\x1fk_EAuthSessionGuardType_UnknownR\bcodeType\"r\n" +
	"<CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response\x122\n" +
	"\x15agreement_session_url\x18\a \x01(\tR\x13agreementSessionUrl*\xb9\x01\n" +
	"\x16EAuthTokenPlatformType\x12$\n" +
	" k_EAuthTokenPlatformType_Unknown\x10\x00\x12(\n" +
	"$k_EAuthTokenPlatformType_SteamClient\x10\x01\x12'\n" +
	"#k_EAuthTokenPlatformType_WebBrowser\x10\x02\x12&\n" +
	"\"k_EAuthTokenPlatformType_MobileApp\x10\x03*\xe5\x02\n" +
	"\x15EAuthSessionGuardType\x12#\n" +
	"\x1fk_EAuthSessionGuardType_Unknown\x10\x00\x12 \n" +
	"\x1ck_EAuthSessionGuardType_None\x10\x01\x12%\n" +
	"!k_EAuthSessionGuardType_EmailCode\x10\x02\x12&\n" +
	"\"k_EAuthSessionGuardType_DeviceCode\x10\x03\x12.\n" +
	"*k_EAuthSessionGuardType_DeviceConfirmation\x10\x04\x12-\n" +
	")k_EAuthSessionGuardType_EmailConfirmation\x10\x05\x12(\n" +
	"$k_EAuthSessionGuardType_MachineToken\x10\x06\x12-\n" +
	")k_EAuthSessionGuardType_LegacyMachineAuth\x10\aB\x03\x80\x01\x01"

var (
	file_steammessages_auth_steamclient_proto_rawDescOnce sync.Once
	file_steammessages_auth_steamclient_proto_rawDescData []byte
)

func file_steammessages_auth_steamclient_proto_rawDescGZIP() []byte {
	file_steammessages_auth_steamclient_proto_rawDescOnce.Do(func() {
		file_steammessages_auth_steamclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_auth_steamclient_proto_rawDesc), len(file_steammessages_auth_steamclient_proto_rawDesc)))
	})
	return file_steammessages_auth_steamclient_proto_rawDescData
}

var file_steammessages_auth_steamclient_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_steammessages_auth_steamclient_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_steammessages_auth_steamclient_proto_goTypes = []any{
	(EAuthTokenPlatformType)(0),                                          // 0: EAuthTokenPlatformType
	(EAuthSessionGuardType)(0),                                           // 1: EAuthSessionGuardType
	(*CAuthentication_GetPasswordRSAPublicKey_Request)(nil),              // 2: CAuthentication_GetPasswordRSAPublicKey_Request
	(*CAuthentication_GetPasswordRSAPublicKey_Response)(nil),             // 3: CAuthentication_GetPasswordRSAPublicKey_Response
	(*CAuthentication_DeviceDetails)(nil),                                // 4: CAuthentication_DeviceDetails
	(*CAuthentication_AllowedConfirmation)(nil),                          // 5: CAuthentication_AllowedConfirmation
	(*CAuthentication_BeginAuthSessionViaCredentials_Request)(nil),       // 6: CAuthentication_BeginAuthSessionViaCredentials_Request
	(*CAuthentication_BeginAuthSessionViaCredentials_Response)(nil),      // 7: CAuthentication_BeginAuthSessionViaCredentials_Response
	(*CAuthentication_PollAuthSessionStatus_Request)(nil),                // 8: CAuthentication_PollAuthSessionStatus_Request
	(*CAuthentication_PollAuthSessionStatus_Response)(nil),               // 9: CAuthentication_PollAuthSessionStatus_Response
	(*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request)(nil),  // 10: CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request
	(*CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response)(nil), // 11: CAuthentication_UpdateAuthSessionWithSteamGuardCode_Response
	(ESessionPersistence)(0),                                             // 12: ESessionPersistence
}
var file_steammessages_auth_steamclient_proto_depIdxs = []int32{
	0,  // 0: CAuthentication_DeviceDetails.platform_type:type_name -> EAuthTokenPlatformType
	1,  // 1: CAuthentication_AllowedConfirmation.confirmation_type:type_name -> EAuthSessionGuardType
	0,  // 2: CAuthentication_BeginAuthSessionViaCredentials_Request.platform_type:type_name -> EAuthTokenPlatformType
	12, // 3: CAuthentication_BeginAuthSessionViaCredentials_Request.persistence:type_name -> ESessionPersistence
	4,  // 4: CAuthentication_BeginAuthSessionViaCredentials_Request.device_details:type_name -> CAuthentication_DeviceDetails
	5,  // 5: CAuthentication_BeginAuthSessionViaCredentials_Response.allowed_confirmations:type_name -> CAuthentication_AllowedConfirmation
	1,  // 6: CAuthentication_UpdateAuthSessionWithSteamGuardCode_Request.code_type:type_name -> EAuthSessionGuardType
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_steammessages_auth_steamclient_proto_init() }
func file_steammessages_auth_steamclient_proto_init() {
	if File_steammessages_auth_steamclient_proto != nil {
		return
	}
	file_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_auth_steamclient_proto_rawDesc), len(file_steammessages_auth_steamclient_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_auth_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_auth_steamclient_proto_depIdxs,
		EnumInfos:         file_steammessages_auth_steamclient_proto_enumTypes,
		MessageInfos:      file_steammessages_auth_steamclient_proto_msgTypes,
	}.Build()
	File_steammessages_auth_steamclient_proto = out.File
	file_steammessages_auth_steamclient_proto_goTypes = nil
	file_steammessages_auth_steamclient_proto_depIdxs = nil
}
