// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_PullImage_FullMethodName               = "/worker.WorkerService/PullImage"
	WorkerService_CreateInstance_FullMethodName          = "/worker.WorkerService/CreateInstance"
	WorkerService_StartInstance_FullMethodName           = "/worker.WorkerService/StartInstance"
	WorkerService_StopInstance_FullMethodName            = "/worker.WorkerService/StopInstance"
	WorkerService_RemoveInstance_FullMethodName          = "/worker.WorkerService/RemoveInstance"
	WorkerService_InspectInstance_FullMethodName         = "/worker.WorkerService/InspectInstance"
	WorkerService_Exec_FullMethodName                    = "/worker.WorkerService/Exec"
	WorkerService_InstanceLogs_FullMethodName            = "/worker.WorkerService/InstanceLogs"
	WorkerService_InstanceStats_FullMethodName           = "/worker.WorkerService/InstanceStats"
	WorkerService_CreateVolume_FullMethodName            = "/worker.WorkerService/CreateVolume"
	WorkerService_RemoveVolume_FullMethodName            = "/worker.WorkerService/RemoveVolume"
	WorkerService_VolumeSize_FullMethodName              = "/worker.WorkerService/VolumeSize"
	WorkerService_BackupVolume_FullMethodName            = "/worker.WorkerService/BackupVolume"
	WorkerService_RestoreVolume_FullMethodName           = "/worker.WorkerService/RestoreVolume"
	WorkerService_ListFiles_FullMethodName               = "/worker.WorkerService/ListFiles"
	WorkerService_ReadFile_FullMethodName                = "/worker.WorkerService/ReadFile"
	WorkerService_WriteFile_FullMethodName               = "/worker.WorkerService/WriteFile"
	WorkerService_WriteFileStream_FullMethodName         = "/worker.WorkerService/WriteFileStream"
	WorkerService_DeletePath_FullMethodName              = "/worker.WorkerService/DeletePath"
	WorkerService_CreateDirectory_FullMethodName         = "/worker.WorkerService/CreateDirectory"
	WorkerService_RenamePath_FullMethodName              = "/worker.WorkerService/RenamePath"
	WorkerService_DownloadFile_FullMethodName            = "/worker.WorkerService/DownloadFile"
	WorkerService_CopyFromInstance_FullMethodName        = "/worker.WorkerService/CopyFromInstance"
	WorkerService_CopyToInstance_FullMethodName          = "/worker.WorkerService/CopyToInstance"
	WorkerService_CopyDirFromInstance_FullMethodName     = "/worker.WorkerService/CopyDirFromInstance"
	WorkerService_CopyTarToInstance_FullMethodName       = "/worker.WorkerService/CopyTarToInstance"
	WorkerService_WatchInstanceStates_FullMethodName     = "/worker.WorkerService/WatchInstanceStates"
	WorkerService_GetAllInstanceStates_FullMethodName    = "/worker.WorkerService/GetAllInstanceStates"
	WorkerService_ListGameserverInstances_FullMethodName = "/worker.WorkerService/ListGameserverInstances"
	WorkerService_Heartbeat_FullMethodName               = "/worker.WorkerService/Heartbeat"
	WorkerService_PrepareGameScripts_FullMethodName      = "/worker.WorkerService/PrepareGameScripts"
	WorkerService_EnsureDepot_FullMethodName             = "/worker.WorkerService/EnsureDepot"
	WorkerService_DownloadWorkshopItem_FullMethodName    = "/worker.WorkerService/DownloadWorkshopItem"
	WorkerService_CopyDepotToVolume_FullMethodName       = "/worker.WorkerService/CopyDepotToVolume"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService is the gRPC interface between controller and worker agents.
// Maps 1:1 to the Go Worker interface in internal/worker/worker.go.
type WorkerServiceClient interface {
	// Instance lifecycle
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageProgress], error)
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error)
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error)
	RemoveInstance(ctx context.Context, in *RemoveInstanceRequest, opts ...grpc.CallOption) (*RemoveInstanceResponse, error)
	InspectInstance(ctx context.Context, in *InspectInstanceRequest, opts ...grpc.CallOption) (*InspectInstanceResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	InstanceLogs(ctx context.Context, in *InstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	InstanceStats(ctx context.Context, in *InstanceStatsRequest, opts ...grpc.CallOption) (*InstanceStatsResponse, error)
	// Volumes
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
	VolumeSize(ctx context.Context, in *VolumeSizeRequest, opts ...grpc.CallOption) (*VolumeSizeResponse, error)
	BackupVolume(ctx context.Context, in *BackupVolumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	RestoreVolume(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RestoreVolumeRequest, RestoreVolumeResponse], error)
	// File operations
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse], error)
	DeletePath(ctx context.Context, in *DeletePathRequest, opts ...grpc.CallOption) (*DeletePathResponse, error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	RenamePath(ctx context.Context, in *RenamePathRequest, opts ...grpc.CallOption) (*RenamePathResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error)
	// Copy operations (streaming for large data)
	CopyFromInstance(ctx context.Context, in *CopyFromInstanceRequest, opts ...grpc.CallOption) (*CopyFromInstanceResponse, error)
	CopyToInstance(ctx context.Context, in *CopyToInstanceRequest, opts ...grpc.CallOption) (*CopyToInstanceResponse, error)
	CopyDirFromInstance(ctx context.Context, in *CopyDirFromInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	CopyTarToInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyTarToInstanceRequest, CopyTarToInstanceResponse], error)
	// Instance state — authoritative state stream from worker to controller
	WatchInstanceStates(ctx context.Context, in *WatchInstanceStatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceStateUpdate], error)
	GetAllInstanceStates(ctx context.Context, in *GetAllInstanceStatesRequest, opts ...grpc.CallOption) (*GetAllInstanceStatesResponse, error)
	// Discovery
	ListGameserverInstances(ctx context.Context, in *ListGameserverInstancesRequest, opts ...grpc.CallOption) (*ListGameserverInstancesResponse, error)
	// Health
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Game scripts — worker extracts scripts locally from embedded game data
	PrepareGameScripts(ctx context.Context, in *PrepareGameScriptsRequest, opts ...grpc.CallOption) (*PrepareGameScriptsResponse, error)
	// Steam depot — worker downloads game files, streams progress back
	EnsureDepot(ctx context.Context, in *EnsureDepotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureDepotProgress], error)
	// Steam Workshop — download a UGC item to a volume path
	DownloadWorkshopItem(ctx context.Context, in *DownloadWorkshopItemRequest, opts ...grpc.CallOption) (*DownloadWorkshopItemResponse, error)
	// Copy depot files to volume — done host-side to avoid container OOM on large depots
	CopyDepotToVolume(ctx context.Context, in *CopyDepotToVolumeRequest, opts ...grpc.CallOption) (*CopyDepotToVolumeResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_PullImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, PullImageProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_PullImageClient = grpc.ServerStreamingClient[PullImageProgress]

func (c *workerServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RemoveInstance(ctx context.Context, in *RemoveInstanceRequest, opts ...grpc.CallOption) (*RemoveInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_RemoveInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) InspectInstance(ctx context.Context, in *InspectInstanceRequest, opts ...grpc.CallOption) (*InspectInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_InspectInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, WorkerService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) InstanceLogs(ctx context.Context, in *InstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[1], WorkerService_InstanceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstanceLogsRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_InstanceLogsClient = grpc.ServerStreamingClient[DataChunk]

func (c *workerServiceClient) InstanceStats(ctx context.Context, in *InstanceStatsRequest, opts ...grpc.CallOption) (*InstanceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceStatsResponse)
	err := c.cc.Invoke(ctx, WorkerService_InstanceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVolumeResponse)
	err := c.cc.Invoke(ctx, WorkerService_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) VolumeSize(ctx context.Context, in *VolumeSizeRequest, opts ...grpc.CallOption) (*VolumeSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeSizeResponse)
	err := c.cc.Invoke(ctx, WorkerService_VolumeSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) BackupVolume(ctx context.Context, in *BackupVolumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[2], WorkerService_BackupVolume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupVolumeRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_BackupVolumeClient = grpc.ServerStreamingClient[DataChunk]

func (c *workerServiceClient) RestoreVolume(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RestoreVolumeRequest, RestoreVolumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[3], WorkerService_RestoreVolume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RestoreVolumeRequest, RestoreVolumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_RestoreVolumeClient = grpc.ClientStreamingClient[RestoreVolumeRequest, RestoreVolumeResponse]

func (c *workerServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[4], WorkerService_WriteFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileStreamRequest, WriteFileStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_WriteFileStreamClient = grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse]

func (c *workerServiceClient) DeletePath(ctx context.Context, in *DeletePathRequest, opts ...grpc.CallOption) (*DeletePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePathResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeletePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RenamePath(ctx context.Context, in *RenamePathRequest, opts ...grpc.CallOption) (*RenamePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenamePathResponse)
	err := c.cc.Invoke(ctx, WorkerService_RenamePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_DownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CopyFromInstance(ctx context.Context, in *CopyFromInstanceRequest, opts ...grpc.CallOption) (*CopyFromInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyFromInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_CopyFromInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CopyToInstance(ctx context.Context, in *CopyToInstanceRequest, opts ...grpc.CallOption) (*CopyToInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyToInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_CopyToInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CopyDirFromInstance(ctx context.Context, in *CopyDirFromInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[5], WorkerService_CopyDirFromInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyDirFromInstanceRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_CopyDirFromInstanceClient = grpc.ServerStreamingClient[DataChunk]

func (c *workerServiceClient) CopyTarToInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyTarToInstanceRequest, CopyTarToInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[6], WorkerService_CopyTarToInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyTarToInstanceRequest, CopyTarToInstanceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_CopyTarToInstanceClient = grpc.ClientStreamingClient[CopyTarToInstanceRequest, CopyTarToInstanceResponse]

func (c *workerServiceClient) WatchInstanceStates(ctx context.Context, in *WatchInstanceStatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceStateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[7], WorkerService_WatchInstanceStates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchInstanceStatesRequest, InstanceStateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_WatchInstanceStatesClient = grpc.ServerStreamingClient[InstanceStateUpdate]

func (c *workerServiceClient) GetAllInstanceStates(ctx context.Context, in *GetAllInstanceStatesRequest, opts ...grpc.CallOption) (*GetAllInstanceStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllInstanceStatesResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetAllInstanceStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListGameserverInstances(ctx context.Context, in *ListGameserverInstancesRequest, opts ...grpc.CallOption) (*ListGameserverInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGameserverInstancesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListGameserverInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) PrepareGameScripts(ctx context.Context, in *PrepareGameScriptsRequest, opts ...grpc.CallOption) (*PrepareGameScriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareGameScriptsResponse)
	err := c.cc.Invoke(ctx, WorkerService_PrepareGameScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) EnsureDepot(ctx context.Context, in *EnsureDepotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureDepotProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[8], WorkerService_EnsureDepot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnsureDepotRequest, EnsureDepotProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_EnsureDepotClient = grpc.ServerStreamingClient[EnsureDepotProgress]

func (c *workerServiceClient) DownloadWorkshopItem(ctx context.Context, in *DownloadWorkshopItemRequest, opts ...grpc.CallOption) (*DownloadWorkshopItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadWorkshopItemResponse)
	err := c.cc.Invoke(ctx, WorkerService_DownloadWorkshopItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CopyDepotToVolume(ctx context.Context, in *CopyDepotToVolumeRequest, opts ...grpc.CallOption) (*CopyDepotToVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyDepotToVolumeResponse)
	err := c.cc.Invoke(ctx, WorkerService_CopyDepotToVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService is the gRPC interface between controller and worker agents.
// Maps 1:1 to the Go Worker interface in internal/worker/worker.go.
type WorkerServiceServer interface {
	// Instance lifecycle
	PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageProgress]) error
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error)
	StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error)
	RemoveInstance(context.Context, *RemoveInstanceRequest) (*RemoveInstanceResponse, error)
	InspectInstance(context.Context, *InspectInstanceRequest) (*InspectInstanceResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	InstanceLogs(*InstanceLogsRequest, grpc.ServerStreamingServer[DataChunk]) error
	InstanceStats(context.Context, *InstanceStatsRequest) (*InstanceStatsResponse, error)
	// Volumes
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
	VolumeSize(context.Context, *VolumeSizeRequest) (*VolumeSizeResponse, error)
	BackupVolume(*BackupVolumeRequest, grpc.ServerStreamingServer[DataChunk]) error
	RestoreVolume(grpc.ClientStreamingServer[RestoreVolumeRequest, RestoreVolumeResponse]) error
	// File operations
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	WriteFileStream(grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]) error
	DeletePath(context.Context, *DeletePathRequest) (*DeletePathResponse, error)
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	RenamePath(context.Context, *RenamePathRequest) (*RenamePathResponse, error)
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error)
	// Copy operations (streaming for large data)
	CopyFromInstance(context.Context, *CopyFromInstanceRequest) (*CopyFromInstanceResponse, error)
	CopyToInstance(context.Context, *CopyToInstanceRequest) (*CopyToInstanceResponse, error)
	CopyDirFromInstance(*CopyDirFromInstanceRequest, grpc.ServerStreamingServer[DataChunk]) error
	CopyTarToInstance(grpc.ClientStreamingServer[CopyTarToInstanceRequest, CopyTarToInstanceResponse]) error
	// Instance state — authoritative state stream from worker to controller
	WatchInstanceStates(*WatchInstanceStatesRequest, grpc.ServerStreamingServer[InstanceStateUpdate]) error
	GetAllInstanceStates(context.Context, *GetAllInstanceStatesRequest) (*GetAllInstanceStatesResponse, error)
	// Discovery
	ListGameserverInstances(context.Context, *ListGameserverInstancesRequest) (*ListGameserverInstancesResponse, error)
	// Health
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Game scripts — worker extracts scripts locally from embedded game data
	PrepareGameScripts(context.Context, *PrepareGameScriptsRequest) (*PrepareGameScriptsResponse, error)
	// Steam depot — worker downloads game files, streams progress back
	EnsureDepot(*EnsureDepotRequest, grpc.ServerStreamingServer[EnsureDepotProgress]) error
	// Steam Workshop — download a UGC item to a volume path
	DownloadWorkshopItem(context.Context, *DownloadWorkshopItemRequest) (*DownloadWorkshopItemResponse, error)
	// Copy depot files to volume — done host-side to avoid container OOM on large depots
	CopyDepotToVolume(context.Context, *CopyDepotToVolumeRequest) (*CopyDepotToVolumeResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageProgress]) error {
	return status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedWorkerServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedWorkerServiceServer) RemoveInstance(context.Context, *RemoveInstanceRequest) (*RemoveInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveInstance not implemented")
}
func (UnimplementedWorkerServiceServer) InspectInstance(context.Context, *InspectInstanceRequest) (*InspectInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectInstance not implemented")
}
func (UnimplementedWorkerServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkerServiceServer) InstanceLogs(*InstanceLogsRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method InstanceLogs not implemented")
}
func (UnimplementedWorkerServiceServer) InstanceStats(context.Context, *InstanceStatsRequest) (*InstanceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstanceStats not implemented")
}
func (UnimplementedWorkerServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedWorkerServiceServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedWorkerServiceServer) VolumeSize(context.Context, *VolumeSizeRequest) (*VolumeSizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VolumeSize not implemented")
}
func (UnimplementedWorkerServiceServer) BackupVolume(*BackupVolumeRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method BackupVolume not implemented")
}
func (UnimplementedWorkerServiceServer) RestoreVolume(grpc.ClientStreamingServer[RestoreVolumeRequest, RestoreVolumeResponse]) error {
	return status.Error(codes.Unimplemented, "method RestoreVolume not implemented")
}
func (UnimplementedWorkerServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedWorkerServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkerServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkerServiceServer) WriteFileStream(grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFileStream not implemented")
}
func (UnimplementedWorkerServiceServer) DeletePath(context.Context, *DeletePathRequest) (*DeletePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePath not implemented")
}
func (UnimplementedWorkerServiceServer) CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedWorkerServiceServer) RenamePath(context.Context, *RenamePathRequest) (*RenamePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenamePath not implemented")
}
func (UnimplementedWorkerServiceServer) DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedWorkerServiceServer) CopyFromInstance(context.Context, *CopyFromInstanceRequest) (*CopyFromInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFromInstance not implemented")
}
func (UnimplementedWorkerServiceServer) CopyToInstance(context.Context, *CopyToInstanceRequest) (*CopyToInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyToInstance not implemented")
}
func (UnimplementedWorkerServiceServer) CopyDirFromInstance(*CopyDirFromInstanceRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method CopyDirFromInstance not implemented")
}
func (UnimplementedWorkerServiceServer) CopyTarToInstance(grpc.ClientStreamingServer[CopyTarToInstanceRequest, CopyTarToInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method CopyTarToInstance not implemented")
}
func (UnimplementedWorkerServiceServer) WatchInstanceStates(*WatchInstanceStatesRequest, grpc.ServerStreamingServer[InstanceStateUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchInstanceStates not implemented")
}
func (UnimplementedWorkerServiceServer) GetAllInstanceStates(context.Context, *GetAllInstanceStatesRequest) (*GetAllInstanceStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllInstanceStates not implemented")
}
func (UnimplementedWorkerServiceServer) ListGameserverInstances(context.Context, *ListGameserverInstancesRequest) (*ListGameserverInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGameserverInstances not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) PrepareGameScripts(context.Context, *PrepareGameScriptsRequest) (*PrepareGameScriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareGameScripts not implemented")
}
func (UnimplementedWorkerServiceServer) EnsureDepot(*EnsureDepotRequest, grpc.ServerStreamingServer[EnsureDepotProgress]) error {
	return status.Error(codes.Unimplemented, "method EnsureDepot not implemented")
}
func (UnimplementedWorkerServiceServer) DownloadWorkshopItem(context.Context, *DownloadWorkshopItemRequest) (*DownloadWorkshopItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadWorkshopItem not implemented")
}
func (UnimplementedWorkerServiceServer) CopyDepotToVolume(context.Context, *CopyDepotToVolumeRequest) (*CopyDepotToVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyDepotToVolume not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).PullImage(m, &grpc.GenericServerStream[PullImageRequest, PullImageProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_PullImageServer = grpc.ServerStreamingServer[PullImageProgress]

func _WorkerService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RemoveInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RemoveInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RemoveInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RemoveInstance(ctx, req.(*RemoveInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_InspectInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).InspectInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_InspectInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).InspectInstance(ctx, req.(*InspectInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_InstanceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstanceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).InstanceLogs(m, &grpc.GenericServerStream[InstanceLogsRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_InstanceLogsServer = grpc.ServerStreamingServer[DataChunk]

func _WorkerService_InstanceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).InstanceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_InstanceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).InstanceStats(ctx, req.(*InstanceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_VolumeSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).VolumeSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_VolumeSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).VolumeSize(ctx, req.(*VolumeSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_BackupVolume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupVolumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).BackupVolume(m, &grpc.GenericServerStream[BackupVolumeRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_BackupVolumeServer = grpc.ServerStreamingServer[DataChunk]

func _WorkerService_RestoreVolume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).RestoreVolume(&grpc.GenericServerStream[RestoreVolumeRequest, RestoreVolumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_RestoreVolumeServer = grpc.ClientStreamingServer[RestoreVolumeRequest, RestoreVolumeResponse]

func _WorkerService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WriteFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).WriteFileStream(&grpc.GenericServerStream[WriteFileStreamRequest, WriteFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_WriteFileStreamServer = grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]

func _WorkerService_DeletePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeletePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeletePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeletePath(ctx, req.(*DeletePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RenamePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenamePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RenamePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RenamePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RenamePath(ctx, req.(*RenamePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CopyFromInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFromInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CopyFromInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CopyFromInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CopyFromInstance(ctx, req.(*CopyFromInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CopyToInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyToInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CopyToInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CopyToInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CopyToInstance(ctx, req.(*CopyToInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CopyDirFromInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyDirFromInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).CopyDirFromInstance(m, &grpc.GenericServerStream[CopyDirFromInstanceRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_CopyDirFromInstanceServer = grpc.ServerStreamingServer[DataChunk]

func _WorkerService_CopyTarToInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).CopyTarToInstance(&grpc.GenericServerStream[CopyTarToInstanceRequest, CopyTarToInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_CopyTarToInstanceServer = grpc.ClientStreamingServer[CopyTarToInstanceRequest, CopyTarToInstanceResponse]

func _WorkerService_WatchInstanceStates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchInstanceStatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).WatchInstanceStates(m, &grpc.GenericServerStream[WatchInstanceStatesRequest, InstanceStateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_WatchInstanceStatesServer = grpc.ServerStreamingServer[InstanceStateUpdate]

func _WorkerService_GetAllInstanceStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInstanceStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetAllInstanceStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetAllInstanceStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetAllInstanceStates(ctx, req.(*GetAllInstanceStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListGameserverInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGameserverInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListGameserverInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListGameserverInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListGameserverInstances(ctx, req.(*ListGameserverInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_PrepareGameScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareGameScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).PrepareGameScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_PrepareGameScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).PrepareGameScripts(ctx, req.(*PrepareGameScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_EnsureDepot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnsureDepotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).EnsureDepot(m, &grpc.GenericServerStream[EnsureDepotRequest, EnsureDepotProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_EnsureDepotServer = grpc.ServerStreamingServer[EnsureDepotProgress]

func _WorkerService_DownloadWorkshopItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadWorkshopItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DownloadWorkshopItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DownloadWorkshopItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DownloadWorkshopItem(ctx, req.(*DownloadWorkshopItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CopyDepotToVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyDepotToVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CopyDepotToVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CopyDepotToVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CopyDepotToVolume(ctx, req.(*CopyDepotToVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstance",
			Handler:    _WorkerService_CreateInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _WorkerService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _WorkerService_StopInstance_Handler,
		},
		{
			MethodName: "RemoveInstance",
			Handler:    _WorkerService_RemoveInstance_Handler,
		},
		{
			MethodName: "InspectInstance",
			Handler:    _WorkerService_InspectInstance_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _WorkerService_Exec_Handler,
		},
		{
			MethodName: "InstanceStats",
			Handler:    _WorkerService_InstanceStats_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _WorkerService_CreateVolume_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _WorkerService_RemoveVolume_Handler,
		},
		{
			MethodName: "VolumeSize",
			Handler:    _WorkerService_VolumeSize_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkerService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _WorkerService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkerService_WriteFile_Handler,
		},
		{
			MethodName: "DeletePath",
			Handler:    _WorkerService_DeletePath_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _WorkerService_CreateDirectory_Handler,
		},
		{
			MethodName: "RenamePath",
			Handler:    _WorkerService_RenamePath_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _WorkerService_DownloadFile_Handler,
		},
		{
			MethodName: "CopyFromInstance",
			Handler:    _WorkerService_CopyFromInstance_Handler,
		},
		{
			MethodName: "CopyToInstance",
			Handler:    _WorkerService_CopyToInstance_Handler,
		},
		{
			MethodName: "GetAllInstanceStates",
			Handler:    _WorkerService_GetAllInstanceStates_Handler,
		},
		{
			MethodName: "ListGameserverInstances",
			Handler:    _WorkerService_ListGameserverInstances_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerService_Heartbeat_Handler,
		},
		{
			MethodName: "PrepareGameScripts",
			Handler:    _WorkerService_PrepareGameScripts_Handler,
		},
		{
			MethodName: "DownloadWorkshopItem",
			Handler:    _WorkerService_DownloadWorkshopItem_Handler,
		},
		{
			MethodName: "CopyDepotToVolume",
			Handler:    _WorkerService_CopyDepotToVolume_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullImage",
			Handler:       _WorkerService_PullImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstanceLogs",
			Handler:       _WorkerService_InstanceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BackupVolume",
			Handler:       _WorkerService_BackupVolume_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestoreVolume",
			Handler:       _WorkerService_RestoreVolume_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WriteFileStream",
			Handler:       _WorkerService_WriteFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyDirFromInstance",
			Handler:       _WorkerService_CopyDirFromInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CopyTarToInstance",
			Handler:       _WorkerService_CopyTarToInstance_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchInstanceStates",
			Handler:       _WorkerService_WatchInstanceStates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EnsureDepot",
			Handler:       _WorkerService_EnsureDepot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}

const (
	ControllerService_Register_FullMethodName          = "/worker.ControllerService/Register"
	ControllerService_Heartbeat_FullMethodName         = "/worker.ControllerService/Heartbeat"
	ControllerService_ValidateSFTPLogin_FullMethodName = "/worker.ControllerService/ValidateSFTPLogin"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControllerService runs on the controller and accepts worker registrations/heartbeats.
type ControllerServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ValidateSFTPLogin(ctx context.Context, in *SFTPLoginRequest, opts ...grpc.CallOption) (*SFTPLoginResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControllerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControllerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ValidateSFTPLogin(ctx context.Context, in *SFTPLoginRequest, opts ...grpc.CallOption) (*SFTPLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SFTPLoginResponse)
	err := c.cc.Invoke(ctx, ControllerService_ValidateSFTPLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
//
// ControllerService runs on the controller and accepts worker registrations/heartbeats.
type ControllerServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ValidateSFTPLogin(context.Context, *SFTPLoginRequest) (*SFTPLoginResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControllerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControllerServiceServer) ValidateSFTPLogin(context.Context, *SFTPLoginRequest) (*SFTPLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSFTPLogin not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ValidateSFTPLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SFTPLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ValidateSFTPLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ValidateSFTPLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ValidateSFTPLogin(ctx, req.(*SFTPLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControllerService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControllerService_Heartbeat_Handler,
		},
		{
			MethodName: "ValidateSFTPLogin",
			Handler:    _ControllerService_ValidateSFTPLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
