#!/bin/bash
set -e

echo "[install-server] downloading Valheim dedicated server via SteamCMD (app 896660)"
steamcmd-retry \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 896660 validate \
    +quit

echo "[install-server] Valheim dedicated server installed"
