#!/bin/bash
set -e

echo "[update-server] updating Valheim dedicated server via SteamCMD"
steamcmd.sh \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 896660 validate \
    +quit

echo "[update-server] update complete"
