#!/bin/bash
set -e

echo "[update-server] updating Palworld dedicated server via SteamCMD"
steamcmd-retry \
    +force_install_dir /data/server \
    +login anonymous \
    +app_update 2394010 validate \
    +quit

echo "[update-server] update complete"
